### ISSUE TITLE
Response not Appear in the chat

### ISSUE THREAD

**Issue by chenqiangpan** [mayooear/gpt4-pdf-chatbot-langchain#101]
Book ingest done, and I could see incoming prompt at OpenAI Language model usage page.

The response is not showing in the chat flow.

![image](https://user-images.githubusercontent.com/8666933/229287779-e447e9bc-0afe-4388-89e5-d406ce55822b.png)

the last lines in the terminal:

 data: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [ClientRequest],
      responseUrl: 'https://api.openai.com/v1/chat/completions',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 22,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

**Comment by hungt23** [comment]
Hi, I'm also encountering this. Did you mark it as complete because it just took a really long time to run or you figured it out on your own?

**Comment by chenqiangpan** [comment]
> Hi, I'm also encountering this. Did you mark it as complete because it just took a really long time to run or you figured it out on your own?

Hi I fixed this issue by changing the model from 4.0 to 3.5 turbo .

Hope it helps.

**Comment by hungt23** [comment]
Hi! Thank you for responding so quickly!  I'm already running on 3.5 turbo :/ I might just let it run a bit more to see if anything happens
