### ISSUE TITLE
search a way to download the pdfs of the source

### ISSUE THREAD

**Issue by quito96** [mayooear/gpt4-pdf-chatbot-langchain#102]
Hi Mayo, 
thank you so much for this great peace of software. 
Works out of the Box.

Is there any way to make the PDFs displayed in the chat, at source, available for download from the server? That would be a mega cool feature.

Thanks for tips

**Comment by g1henx** [comment]
Hello, my approach for this case was to upload the docs to Firebase Storage when ingesting them. Then make sure to use the doc name when reffering to the source in the vectors for then being able to delete them.
