### ISSUE TITLE
managed to ingest but there is an error with fetching

### ISSUE THREAD

**Issue by text2sql** [mayooear/gpt4-pdf-chatbot-langchain#103]
error [Error: PineconeClient: Error calling query: Error: PineconeClient: Error calling queryRaw: FetchError: The request failed and the interceptors did not return an alternative response] 
the index and namespace with vectors show on the Pinecone side ok. 
anyone experienced the same?

**Comment by naticio** [comment]
meeeee

**Comment by johnydodger** [comment]
I think I'm having a similar issue?  on my pinecone dashboard, I see the correct namespace and number of vectors, but the "fetch" function just fetches an empty set.

**Comment by reggieharris** [comment]
> I think I'm having a similar issue? on my pinecone dashboard, I see the correct namespace and number of vectors, but the "fetch" function just fetches an empty set.

Same

**Comment by Arham-12336** [comment]
same.. Any luck with that?

**Comment by Arham-12336** [comment]
> error [Error: PineconeClient: Error calling query: Error: PineconeClient: Error calling queryRaw: FetchError: The request failed and the interceptors did not return an alternative response] the index and namespace with vectors show on the Pinecone side ok. anyone experienced the same?

same.. Any luck with that?

**Comment by TextToSQL** [comment]
for anyone struggling to get Mayo's code working, what worked for me is a combination of Mayo's code + this code https://github.com/misbahsy/chat-with-twitter-algorithm-ml . I would use Mayo's code for creating and storing vectors on Pinecone (pnpm run ingest), and the Misbahsy code for fetching and getting the chat up and running (without the ingestion part). I hope Mayo can fix some of the issues soon.

**Comment by Arham-12336** [comment]
@TextToSQL can you explain me where to look specifically for the problem. Thanks for the help

**Comment by Arham-12336** [comment]
Thanks for sharing

**Comment by Hanser256** [comment]
I'm having the same problem. The vectors are being created as expected, but seem to be empty after fetching.

**Comment by willeswa** [comment]
This is most likely an issue to do with initializing pinecone. In my case, I wasn't passing the right index name here 
```const pineconeIndex = client.Index(process.env.INDEX_NAME!);```
Just double-check to make sure that you getting everything right .

**Comment by Sine-Of-Time** [comment]
> This is most likely an issue to do with initializing pinecone. In my case, I wasn't passing the right index name here `const pineconeIndex = client.Index(process.env.INDEX_NAME!);` Just double-check to make sure that you getting everything right .

How did you fix your issue?
