### ISSUE TITLE
Error: Failed to ingest your data

### ISSUE THREAD

**Issue by josh-may** [mayooear/gpt4-pdf-chatbot-langchain#108]
Anyone else experience this? I tried with the PDFs included in the repo as well as others. Below is the error - "request failed and the interceptors did not return an alternative response".

https://user-images.githubusercontent.com/72312238/229350817-97b01233-086e-486c-bf4a-f206d8917d30.mov

```
creating vector store...
error [Error: PineconeClient: Error calling upsert: Error: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response]
/Users/joshmay/Desktop/untitled folder/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:45
    throw new Error('Failed to ingest your data');
          ^
[Error: Failed to ingest your data]
```

I added a console log inside ingest-data.ts. Which shows my api key and environment. And everything looks good. 

```
  PineconeClient {
  apiKey: 'xxxxxxxxxxxxx',
  projectName: '683d1ab',
  environment: 'us-west4-gcp',
  configureIndexRaw: [Function (anonymous)],
  configureIndex: [Function (anonymous)],
  createCollectionRaw: [Function (anonymous)],
  createCollection: [Function (anonymous)],
  createIndexRaw: [Function (anonymous)],
  createIndex: [Function (anonymous)],
  deleteCollectionRaw: [Function (anonymous)],
  deleteCollection: [Function (anonymous)],
  deleteIndexRaw: [Function (anonymous)],
  deleteIndex: [Function (anonymous)],
  describeCollectionRaw: [Function (anonymous)],
  describeCollection: [Function (anonymous)],
  describeIndexRaw: [Function (anonymous)],
  describeIndex: [Function (anonymous)],
  listCollectionsRaw: [Function (anonymous)],
  listCollections: [Function (anonymous)],
  listIndexesRaw: [Function (anonymous)],
  listIndexes: [Function (anonymous)]
}
```

**Comment by obaeyaert** [comment]
Had the same problem earlier, it was related with my PINECONE_INDEX_NAME
Just add the "short"name ("dic" in the screenshot)

![image](https://user-images.githubusercontent.com/3645753/229357305-59b3d04e-6bf8-4da3-8414-42a550e34e31.png)

**Comment by jmesplana** [comment]
I had exactly the same problem last night. It was related to OpenAI api. My api expired and I ended up adding a CC to my account then it worked again.

**Comment by bahram-ghahari** [comment]
Yes I traced it back to openai.createEmbedding(...) method. I had to write a helper method and use axios. Not pretty but got it done.

**Comment by prophesy604** [comment]
i got 429 error when i try to ingest turingfinance.pdf , do you? i have the starter plan with pinecone

**Comment by smiley717** [comment]
it will help to solve this issue from this [link](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/97#issuecomment-1494136731)

**Comment by MuhammadIshaq-AI** [comment]
I am having the same issue, what shall I do ?
