### ISSUE TITLE
Is it possible to use Postgres/Mysql instead of Pinecone?

### ISSUE THREAD

**Issue by johnsonjsyuen** [mayooear/gpt4-pdf-chatbot-langchain#110]
Just wondering if it's possible to use something other than Pinecone, to reduce the dependencies. Postgres has extensions for vector storage https://github.com/pgvector/pgvector

**Comment by sime2408** [comment]
Pinecone is a vector database, PostgreSQL is not specifically designed for handling high-dimensional vector data, but I assume you should be able to store vector embeddings as arrays or binary data. Searching and retrieving similar vectors won't be as efficient as using a dedicated vector database though. Extensions like pgvector or pgroonga are for that indeed, and if you don't want to mess up with the backend for upsert & query you can expose Postgres using let's say stored functions via PostgREST

**Comment by darkomking** [comment]
https://supabase.com/docs/guides/database/extensions/pgvector definitely possible, although Pinecone is specialized for the task.

**Comment by zenzjtech** [comment]
Are there any updates regarding this topic?
