### ISSUE TITLE
Get Responses Outside the document

### ISSUE THREAD

**Issue by disocodes** [mayooear/gpt4-pdf-chatbot-langchain#112]
Thank you for the project, I tested it out with a different document and it worked well with a few mismatches. However how can I make the chatbot respond to questions out of the document as I have asked the bot simple questions like "Hi Chatbot, I have a question" and it start to hallucinate answers from the extracted parts. I have tried reading lanchain's documentation but cant work my way around. Is there a way to have chatbot engage in general conversations as guided by another prompt but then once a specific question relates to the extracted parts the bot then attempts to get answer from the document?

**Comment by dmitrii-brand** [comment]
I think you need to change QA_PROMPT and remove lines where chagpt is asked to not provide info outside of context.

**Comment by Lionardo** [comment]
I would also be interested in this feature. Did anyone figure out a way?
one way that I tried to go about this was to check if the response has a string of "Hmm" since this is the default response for not finding the answer and then construct a ```conversationChain```
