### ISSUE TITLE
Does it work in other languages than english?

### ISSUE THREAD

**Issue by luisrock** [mayooear/gpt4-pdf-chatbot-langchain#123]
I am trying with a pdf in portuguese and the results are awful. I've updated the prompt, but still...

**Comment by yinshipeng** [comment]
I also encountered the same problem. I am trying to use the Chinese document, but the effect is not very good

**Comment by stefansms** [comment]
Can you describe it's behavior?

I translated the QA_PROMPT and CONDENSE_PROMPT to portuguese. Ingested some portuguese PDF and it's working as expected, answering in Portuguese.

However, it fails to connect one question to another, as if it stays stuck on the initial results and don't seem to "refresh" them.  I don't think it is related to the translation.

**Comment by luisrock** [comment]
Well, my PDF has 200 pages. Must be a problem, right? The context (sources) are not at all related to the question. So I guess the problem is in the search for the right context to inject in the prompt

**Comment by lucastzuka** [comment]
I tried hard to make it work in Portuguese, but it didn't work :/ If you manage to make it work, please let me know

**Comment by stefansms** [comment]
@luisrock 
This may be true, but this limitation should not force the template to respond in English. In my case, I am using gpt3.5-turbo as model and have provided more than 2000 pages of PDF in Portuguese.

@lucastzuka 
I've just translated the prompt, as mentioned earlier.  I also provided a lot of text in Portuguese.

**Comment by luisrock** [comment]
Again, the context injected is totally wrong. That is the main reason, I guess.

**Comment by lucastzuka** [comment]
@luisrock talvez de uma olhada se os pdf que vc ta usando nao estao protegidos. pra mim deu uns problemas de contexto no chat e fazendo perguntas especificas de cada documento percebi que um dos 3 pdf que eu tinha carregado estava protegido. outra coisa que vi que pode ser tambem é quando as paginas de texto do pdf estao convertidas em imagem.

@stefansms I translated the QA_PROMPT to Portuguese and added a line saying to give the answers in Portuguese. So it worked :) even when loading only documents in English. thanks s2

**Comment by snarb** [comment]
Chat model not in English works incorrectly. OpenAi works with same prompt.

**Comment by thiagopachecoit** [comment]
I think this pull request may help: https://github.com/mayooear/gpt4-pdf-chatbot-langchain/pull/77

**Comment by ahgsql** [comment]
Its not about answers from GPT, the problem is about to find related chunks
