### ISSUE TITLE
npm run injest error!

### ISSUE THREAD

**Issue by xiaomingcom-cs** [mayooear/gpt4-pdf-chatbot-langchain#128]
![image](https://user-images.githubusercontent.com/75123667/229848135-bb237d1d-7c20-4118-abda-293580d1be24.png)

**Comment by Arham-12336** [comment]
May this code help

``tjs
    const chunkSize = 50;
    for (let i = 0; i < docs.length; i += chunkSize) {
      const chunk = docs.slice(i, i + chunkSize);
      console.log('chunk', i, chunk);
      await PineconeStore.fromDocuments(
          chunk,
          embeddings,
          {
            textKey: 'text',
            pineconeIndex: index,
            namespace: 'PINECONE_NAMESPACE',
          }
      );
```

**Comment by xiaomingcom-cs** [comment]
Thank you,but the problem still exists. the status code 429 stands for too many requests, maybe I use the free account that limits my upload time, Are you using a free account?

**Comment by AyoCodess** [comment]
> ```js
> const chunkSize = 50;
>     for (let i = 0; i < docs.length; i += chunkSize) {
>       const chunk = docs.slice(i, i + chunkSize);
>       console.log('chunk', i, chunk);
>       await PineconeStore.fromDocuments(
>           chunk,
>           embeddings,
>           {
>             textKey: 'text',
>             pineconeIndex: index,
>             namespace: 'PINECONE_NAMESPACE',
>           }
>       );
> ```

i have the same issue, did you solve it?
