### ISSUE TITLE
How to output links ?

### ISSUE THREAD

**Issue by yanndine** [mayooear/gpt4-pdf-chatbot-langchain#129]
In the beginning of your tutorial video, the chatbot replies with links to actual websites _(See Wood v. Strickland, 420 U. S. 308, 314, n. 6 (1975))_

Using the same prompts, I do get the same answer as you but there isn't any link, it's just plain text and pdf references.

How do I get the links as well ?

**Comment by fmcreativeco** [comment]
Edit [makechain.ts](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/blob/main/utils/makechain.ts) and modify the default prompt to include something like this:

"ALWAYS include a properly formatted clickable hyperlink to the PDF source"

**Comment by LeoArtaza** [comment]
> In the beginning of your tutorial video, the chatbot replies with links to actual websites _(See Wood v. Strickland, 420 U. S. 308, 314, n. 6 (1975))_
> 
> Using the same prompts, I do get the same answer as you but there isn't any link, it's just plain text and pdf references.
> 
> How do I get the links as well ?

I was looking for how to do this as well, and I think the secret ingredient in the prompt he used is "Helpful answer **in Markdown**:", with Markdown you can create hyperlinks with custom text.

**Comment by HastiSutaria** [comment]
what to go if we get wrong hyperlinks?
