### ISSUE TITLE
Failed to ingest your data

### ISSUE THREAD

**Issue by fermin-perez** [mayooear/gpt4-pdf-chatbot-langchain#130]
![error](https://user-images.githubusercontent.com/101753600/229930399-56c62c74-35ee-41bf-842b-939543949d13.png)

Pinecone Dashboard
![Pinecone-Console](https://user-images.githubusercontent.com/101753600/229930664-c5384f4f-3b9e-4375-bda7-d997fd00f1cd.png)

.env configuration
![Sin título](https://user-images.githubusercontent.com/101753600/229930792-d66e7799-2acb-4213-89f8-160030edbeb1.png)

When executing the npm run ingest command I get the following error, any solution?

**Comment by ptonewreckin** [comment]
@fermin-perez be sure to rotate your api keys :)

**Comment by fermin-perez** [comment]
> be sure to rotate your api keys :)


Yes, I already uploaded them as an example

**Comment by Arham-12336** [comment]
Carefully check the log there must be some error in the log between these chunks

**Comment by msn1983aa** [comment]
same error information

**Comment by dirac292** [comment]
Had the same issue and tried everything.The solution: Pay for the OpenAI API that is add a credit card there. This is if there is 429 Request error that is too many requests.

**Comment by dogmatic69** [comment]
Also had 429, added cc details and it works.

**Comment by bilersan** [comment]
i also approve adding cc details to openai works for 429 request error

**Comment by brendanjmeade** [comment]
With a paid openai account, I'm seeing the same issue as @fermin-perez .  Thoughts?

**Comment by fermin-perez** [comment]
I have open ai api key pay, and it throws me the same, error 429

**Comment by fermin-perez** [comment]
> También tenía 429, se agregaron detalles de cc y funciona.

What would be the solution to error 429?

**Comment by EnesGit** [comment]
I have the same problem and I already have creditcard details added

**Comment by AdrianV101** [comment]
Don't mean to open a somewhat finished thread, however just a bit of info for people having this issue looking at this in the future, from someone who had and fixed the 429 requests related error: 

- Paying for ChatGPT 4 is not the same as paying for the OpenAI API, this does not resolve it (I already had GPT 4 but this confused me a bit)
- They don't bill your debit/credit until the end of the month
- If you're worried about cost, its close to nothing. I fed it around 128 PDF documents, I would estimate around 20-30 pages average length, and it cost me 25 cents.
- If you are training it on a very large scale, and are still worried about costs, you can set a soft limit, which if your usage cost exceeds, will send you an email alert, and a hard limit which cannot be exceeded by usage, ie. you can't get charged more than this amount. Do note that if your hard limit is exceeded, the API will stop working until you increase the hard limit if you wish to do so.

In relation to people still having the problem with card details added, unfortunately I have no help for you, the only suspicion I have is maybe you are confusing paying for GPT 4 and having the OpenAI API, apologies if this isn't the case and I hope you find a solution. I'm an engineering student, not a programmer, and unfortunately cannot really provide further guidance.

Hope this info clarifies some things for people :)
