### ISSUE TITLE
Only responds once

### ISSUE THREAD

**Issue by lucastzuka** [mayooear/gpt4-pdf-chatbot-langchain#131]
When I ask the first question, the chat responds. But when I ask the second question, the chat avatar appears and the text box appears, but it remains blank, there is no response.

**Comment by Jstaho** [comment]
same

**Comment by danielreiser** [comment]
You probably don't have access to the GPT-4 api yet. change the modelName to e.g. `gpt-3.5-turbo` in `utils/makechain.ts:36`. This should do the trick.
