### ISSUE TITLE
Is it possible to fetch data from txt, json instead of pdf?

### ISSUE THREAD

**Issue by andrew3920029** [mayooear/gpt4-pdf-chatbot-langchain#137]

**Comment by tuantranf** [comment]
@andrew3920029 yes. I tried my side to ingest txt file from local using `TextLoader` of langchain
You can check my sample code here
https://github.com/tuantranf/gpt4-pdf-chatbot-langchain/blob/feature/vietnamese-insurance-law-qa/scripts/ingest-data-text.ts

**Comment by davideuler** [comment]
This project has support of docx, pptx, csv, txt, etc. With open source chromadb instread of Pinecone.
[gpt4-pdf-chatbot-langchain-chromadb](https://github.com/davideuler/gpt4-pdf-chatbot-langchain-chromadb)
