### ISSUE TITLE
langchain/document_loaders has no exported member DocxLoader

### ISSUE THREAD

**Issue by rohanikshvaku** [mayooear/gpt4-pdf-chatbot-langchain#145]
Hi,

I would like to be able to parse DOCX files as well. So as per the langchain js docs, I have installed Mammoth.

Then I added `import { DocxLoader } from "langchain/document_loaders";`

But I get this error: `langchain/document_loaders\"' has no exported member 'DocxLoader'`

Please help me with this. Thanks!

**Comment by bschleter** [comment]
Did you add comment loader below pdf loader in ingest.ts?
