### ISSUE TITLE
Read data from excel/csv

### ISSUE THREAD

**Issue by shaileshp367** [mayooear/gpt4-pdf-chatbot-langchain#146]
I need to read data from excel/csv, also read tabular data from excel sheet because our some reports/documents are available in csv/excel so I request to add this.

**Comment by bahram-ghahari** [comment]
just add a custom csv loader class.
```

export class CustomCSVLoader extends BufferLoader {
  public async parse( raw: Buffer  , metadata: Document['metadata'] ): Promise<Document[]> {
    return [
      new Document({
        metadata,
        pageContent: this.clean(raw.toString())
      }),
    ];
  }


```

then in add the following in `injest-data` script 

```
    const directoryLoader = new DirectoryLoader(filePath, {
      '.pdf': (path) => new CustomPDFLoader(path),
      '.csv': (path) => new CustomCSVLoader(path),
    });
```

**Comment by grabani** [comment]
@bahram-ghahari -to which file does one add the `custom csv loader class`?

**Comment by longfuxu** [comment]
Also wondering if it is possible to read contents from other formats, such as docs, or .md? Thank you

**Comment by braginteractive** [comment]
> just add a custom csv loader class.
> 
> ```
> 
> export class CustomCSVLoader extends BufferLoader {
>   public async parse( raw: Buffer  , metadata: Document['metadata'] ): Promise<Document[]> {
>     return [
>       new Document({
>         metadata,
>         pageContent: this.clean(raw.toString())
>       }),
>     ];
>   }
> ```
> 
> then in add the following in `injest-data` script
> 
> ```
>     const directoryLoader = new DirectoryLoader(filePath, {
>       '.pdf': (path) => new CustomPDFLoader(path),
>       '.csv': (path) => new CustomCSVLoader(path),
>     });
> ```

when did the clean function come from?

**Comment by nagaki09** [comment]
> @longfuxu you can use llama index for that. https://llamahub.ai/ this site has all the loaders which you can think of.

should i copy the code from https://llamahub.ai/ and add to 
![image](https://user-images.githubusercontent.com/31009189/231056791-a27887a8-bfa8-4299-ad1c-62a793989e88.png)
customPDFLoader.ts?

**Comment by bschleter** [comment]
> @bahram-ghahari This is only for csv I need to parse all format for excel files, Please help me

I replied earlier to you about saving csv as a pdf, but also the answer above about adding a csv class as well will work. 

Simple add the csv class into the ingest-data.ts file under the pdf loader.

**Comment by bschleter** [comment]
@shaileshp367 load excel file into excel, or right click save as csv. Then use csv loader as above.
