### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by rmajidy** [mayooear/gpt4-pdf-chatbot-langchain#148]
I'm encountering an "Invalid hook call" error in my Next.js application, specifically a server error "TypeError: Cannot read properties of null (reading 'useContext')".

The warning I'm getting is

`Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

You might have mismatching versions of React and the renderer (such as React DOM)

You might be breaking the Rules of Hooks

You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
at Object.useContext (/Users/me/repos/programming-sandbox/langchain:embeddings/langchain-chat-nextjs/node_modules/react/cjs/react.development.js:1618:21)`

To replicate this issue I just ran "npm run dev" after installing the packages with "npm install".

I have the same versions of React & react DOM (18.2.0) and node v19.4.0

Also there is nowhere in the code where useContext is used.

This could be a noob question so I apologize in advance if it is.

**Comment by doubleweb3** [comment]
how did you solve that?
