### ISSUE TITLE
Ingestion of pdf's does not appear to find data during subsequent chat queries very well, nor broad spans of data

### ISSUE THREAD

**Issue by DXXS** [mayooear/gpt4-pdf-chatbot-langchain#149]
Well, I tried ingesting hundreds of megabytes of data in pdf's ~that I have generated for a project that I've been working on, and subsequent efforts to 'chat' with the data don't seem to be returning great results.

Even examining the very first document seems to have difficulties with returning material past the first 25-30 pages or so (each page of which currently seems to be sliced into a separate 'document', which doesn't even currently have a page number attached to refer back to).

I am wondering if maybe 'denser' vectors might produce better 'search' results?  I see that pinecone has something up on their site about more 'information-rich' vector generation:

https://www.pinecone.io/learn/dense-vector-embeddings-nlp/

Also, currently if I ask questions that might require an examination spanning ~several pages (like ~'how many sections are there'), it seems totally clueless.  Am therefore also wondering if maybe something that'd go back and re-ingest surrounding data in documents after queries might be done somehow in a more useful manner?

**Comment by riceorpasta** [comment]
I had some similar issues and found some tweaks. Maybe this helps:
- I updated the k value in the ChatVectorDBQAChain in the makeChain function. More sources documents were returned. 
- I updated the temperature when initializing the OpenAIChat instances. This helped to get more diverse and longer responses
- I updated the prompt in QA_PROMPT to include more context for my specific usage
These workarounds helped me to get longer, better responses from more resources for my specific use and i'm looking to adding some CombinedContext to the QA_PROMPT to get even more of all the ingested materials, probably having to wait to get access to gpt-4-32k for that as this will likely overpass the token limits

**Comment by awilliamson** [comment]
@DXXS My main observation from tweaking with chunking and overlap is that the ability for the Chatbot to answer my query well is based on a few things:

1.  The ability for the vector store to correctly identify and retrieve context. Cosine similarity on embeddings can only get you so close. If your query is based largely on a single rare word, and a word that is a synonym of the technical term in your corpus, you may struggle to even identify a correct context to give to GPT3.5/GPT4

2. In my use-case, I used PDFs. PDFs seem to be processed quite poorly by default. Chunking is naive and context-unaware. E.g It will arbitrarily chunk even across sections / headings. An ideal solution here would be to have variable chunks and to make chunking context-aware to keep the chunks aligned to a specific notion. E.g Regulations on Carbon Emissions Section 4.3

3. A static K can sometimes be a hindrance, as multiple documents are retrieved and forcibly used (with the default QA_PROMPT). Sometimes 1 document is all I need for a specific lookup, other times I need to collate an answer from multiple sources.

4. My documents are quite long, and each document I want in the knowledge-base shares a large overlap in terminology. Often resulting in the selection of the wrong chunks. Having a pre-processed version of your document as a quick summary might be advantageous for broad-level queries, as this is more likely to be selected and used for an answer. This can sit alongside the high-granularity ones too.

A note on 'temperature': Introducing some entropy is good for the naturalness of interactions. But terrible if you're after rote regurgitation of technical/legal jargon (E.g Specific regulations on carbon emissions...). I don't believe changing this will improve success of the bots ability to find and use the correct context, or extract the correct answer from said context.
5. 

Therefore I recommend to look at more dynamic chunking, or document pre-processing steps. Maybe you chop it up yourself into sub-pdfs first before passing it in. Hope this helps and gets you thinking :)

**Comment by DXXS** [comment]
Hmm; well I halved the limited parameters available 'chunksize' and 'overlap', and got somewhat closer results on that one document (though it somehow split it right between 'DEFINITIONS' and 'means', so I had to ask with 'means' before in subsequent refined queries it acknowledged finding it), but other queries still seem to strangely perplex it.  Oy!

**Comment by DXXS** [comment]
Ah! it looks to me as though, if this project were to add something like this, it might help!  "A Framework for Analyzing and Improving Content-Based Chunking Algorithms" : https://www.hpl.hp.com/techreports/2005/HPL-2005-30R1.pdf

{ Maybe also in association with NTLK? }

**Comment by palef-re** [comment]
does anyone know how to amend the number of source documents?  There no longer appears to be a way to amend K value:   

const chain = ConversationalRetrievalQAChain.fromLLM(
    model,
    vectorstore.asRetriever(),
    {
      qaTemplate: QA_PROMPT,
      questionGeneratorTemplate: CONDENSE_PROMPT,
      returnSourceDocuments: true, //The number of source documents returned is 4 by default, 
    },

**Comment by ladrians** [comment]
@palef-re, it should work setting the value when using the `asRetriever` method, something like `vectorstore.asRetriever(5)`.

**Comment by DXXS** [comment]
FWIW, I was just granted GPT4 developer status (though apparently the API is only accessing the chat model, and something like a davinci-004 isn't available yet).

'Chatting' with my documents appears to be obtaining much better results {also incorporating changes above} (though still some strange ~waffling going on, IMO); however, it did charge me ~$.25 to ingest my data once & ask it a few questions!

**Comment by Robs-Git-Hub** [comment]
> @DXXS My main observation from tweaking with chunking and overlap is that the ability for the Chatbot to answer my query well is based on a few things:
> 3. A static K can sometimes be a hindrance, as multiple documents are retrieved and forcibly used (with the default QA_PROMPT). Sometimes 1 document is all I need for a specific lookup, other times I need to collate an answer from multiple sources.

Thanks for the helpful list.  I was already working on several of your suggestions, but do you have any advice on a simple way to use a not-static k?  Any good implementations of this you'd recommend? Thanks.

**Comment by DXXS** [comment]
I don't consider the issue to be resolved; minor improvements can be achieved by the given modifications, but I haven't seen fixes for the the 'broad spans of data' portion yet at all.

**Comment by DXXS** [comment]
I've seen no responses from the developers that these issues have been substantially fixed; why don't you point us to the evidence?  Managing 'backlog' by claiming that issues have been fixed because no progress has been made?

**Comment by DXXS** [comment]
lame
