### ISSUE TITLE
Extrapolate for Multiple individual pdf docs

### ISSUE THREAD

**Issue by disturbed-mystic1** [mayooear/gpt4-pdf-chatbot-langchain#15]
Can we do this for multiple pdf documents or is it for a single pdf. Sorry I haven't gone through the code yet.

**Comment by mayooear** [comment]
For now it's a single pdf, but I plan to start working on a PR for multiple PDF docs.

**Comment by saxjonas** [comment]
What changes would be required to make it work for multiple documents? I've added a loop in the ingest script to ingest all pdf's in a folder. Are there additional changes that need to be made in order for this to work?
