### ISSUE TITLE
Failed to Ingest Data

### ISSUE THREAD

**Issue by grabani** [mayooear/gpt4-pdf-chatbot-langchain#150]
Hi There,

I am getting the following error when running the `npm run ingest` command:

```creating vector store...
error [Error: PineconeClient: Error calling upsert: Error: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response]
c:\Users\Projects\chatpdf\gpt4-pdf-chatbot-langchain-main\gpt4-pdf-chatbot-langchain-main\scripts\ingest-data.ts:44
    throw new Error('Failed to ingest your data');
          ^


[Error: Failed to ingest your data]

Node.js v18.15.0
```

I have the following configured in my `.env` file:

```
OPENAI_API_KEY='sk-XXXXXXX'

# Update these with your Supabase details from your project settings > API and dashboard settings
PINECONE_API_KEY= '7XXXXXXXXX'
PINECONE_ENVIRONMENT= 'us-east1-gcp'
PINECONE_INDEX_NAME= 'default'
```
I have edited the `pinecone.ts` file and set my namespace to:

`const PINECONE_NAME_SPACE = 'pdfread'; //namespace is optional for your vectors`

Although not relevant at this stage I have edited the `makechain.ts` file to capture I am using GPT-3.5 as I am on the waitinglist for GPT-4:

`modelName: 'gpt-3.5-turbo',`

Finally, the pdf I am using ingesting is the `MorseVsFrederick` which came with the repo.

Any thoughts on what I am doing wrong?

**Comment by brendanjmeade** [comment]
Same situation here.  Guidance welcome.

**Comment by programmeddeath1** [comment]
Same situation here, does the pine code index need to be created directly on pinecone?

**Comment by grabani** [comment]
I didn’t change anything and it is now working. Maybe something to do with the pinecone infrastructure.

**Comment by programmeddeath1** [comment]
Yup, i created an index with 1536 dimensions and cosine. It still failed during run ingest. I then reduced he size of my documents byhalf to around 100 documents of 100kb. It worked after taking sometime to run the ingest. Is possibly a size limit issue on storing in pinecone free setup.

**Comment by mrslimslim** [comment]
face the same issue , and I am considering to use chorma to replace the pinecone

**Comment by phbernard** [comment]
It's worth noting that in `.env`, `PINECONE_INDEX_NAME` is really the name of your index (eg. `myindex`) and not the full domain (eg. `myindex-12345.svc.northamerica-northeast1-gcp.pinecone.io`).

**Comment by Adorp94** [comment]
> It's worth noting that in `.env`, `PINECONE_INDEX_NAME` is really the name of your index (eg. `myindex`) and not the full domain (eg. `myindex-12345.svc.northamerica-northeast1-gcp.pinecone.io`).

Wow, that was it for me! Thanks for the reminder.
