### ISSUE TITLE
Error: PineconeClient: Error calling upsert: Error: PineconeClient: Error calling upsertRaw: no healthy upstream

### ISSUE THREAD

**Issue by sarinstein-yan** [mayooear/gpt4-pdf-chatbot-langchain#152]
I've already referred to other pinecone errors posted (pinecone_index_name being the shorter one; dimension = 1536; checked .env and pinecone.ts)
![图片](https://user-images.githubusercontent.com/98195226/230757723-7c073520-3def-46d5-8e1f-d21865aae996.png)
I don't know whether it's because the pinecone index is "initializing"
![图片](https://user-images.githubusercontent.com/98195226/230758187-ad475009-e5d8-4919-ad63-393cd5ccbd1e.png)
Any help would be appreciated!!

**Comment by sarinstein-yan** [comment]
The pinecone index has been initializing for about two hours...

**Comment by aldudrino** [comment]
similar for me 

error [Error: PineconeClient: Error calling upsert: Error: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response]

**Comment by aldudrino** [comment]
Got solved once PineCone was initialised

**Comment by sarinstein-yan** [comment]
> Got solved once PineCone was initialised

same :)

**Comment by sarinstein-yan** [comment]
solved. pinecone wasn't initialized
