### ISSUE TITLE
How to Read data from excel with multiple sheets?

### ISSUE THREAD

**Issue by shaileshp367** [mayooear/gpt4-pdf-chatbot-langchain#155]
Hi

How to Read data from excel with multiple sheets?

Please help. Thanks

**Comment by bschleter** [comment]
Save your excel or .csv sheets into a pdf. This has only a pdf parser so in its current state doesn't read excel sheets. 

Pdf parse documentation however isn't always perfect, so YMMV.

**Comment by shaileshp367** [comment]
@bschleter @mayooear Any other way to parse excel and use in this

**Comment by mayooear** [comment]
You may need to experiment with various [csv parsers](https://www.npmjs.com/search?q=csv%20parse) to do the "loading" aspect.
