### ISSUE TITLE
Ingest Error  (previously working)

### ISSUE THREAD

**Issue by majumba** [mayooear/gpt4-pdf-chatbot-langchain#157]
Totally stumped as I have had this working fine before with no issues

When i try npm run ingest I am getting the following error:

// Prior to splitting the docs:

PineconeClient: Error getting project name: SyntaxError: Unexpected token A in JSON at position

// The docs are then split correctly and logged correctly.

creating vector store...
error [Error: PineconeClient: Project name not set. Call init() first.]
/Users/steven/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:44
    throw new Error('Failed to ingest your data');

Totally stumped and have spent the last few hours re-cloning the repo, rotating API keys, changing the index name to no avail. Hugely frustrating as I like i said it was working with no issues previously.

My environment is us-central1-gcp. The only thing i have not done is change the Pinecone environment as i do not think its worth the $70 to upgrade if it still does not work.

Any help would be super appreciated

Edit: I have upgraded my version of node to v19.9.0. And before the text splitting begins it gives the following error which provides a bit more insight but I still cannot get it to work: 
PineconeClient: Error getting project name: SyntaxError: Unexpected token 'A', "API key is"... is not valid JSON

**Comment by majumba** [comment]
erhghh there is an issue with my dotenv package. Still have not quite worked it out but if i hardcode the api key it works... well that was frustrating.

API key is".

This is short for API is missing or invalid, in case anyway stumbles across this - updating to a more recent node version made this clearer

**Comment by DialloYoussouf** [comment]
Make a prompt to chatpgt: try this==>
I have this error : SyntaxError: Unexpected token A in JSON at position
With this code : paste the ingest-data.ts code here


You should get an answer

**Comment by majumba** [comment]
thanks. my stupid fault. i had set the pinecone api as a env variable in the shell and it was overriding the local project api key after i rotated the pinecone api key. frustrating but thankfully solved
