### ISSUE TITLE
Issue running 'pnpm install'

### ISSUE THREAD

**Issue by Pantactrum** [mayooear/gpt4-pdf-chatbot-langchain#160]
![image](https://user-images.githubusercontent.com/130513787/231566632-48aec172-a75a-4927-a5a7-04d2dbccf9ad.png)

**Comment by mayooear** [comment]
Use the latest version of the repo. It uses `yarn` instead.

**Comment by bschleter** [comment]
Try yarn, or make sure node & npm is installed in this path/environment. It doesn't appear as if so. 

So run the simple pip install pnpm. 

I had issues with pnpm, and even Yarn permissions installs, so I used npm install to get the dependencies.
