### ISSUE TITLE
fail to ingest error.

### ISSUE THREAD

**Issue by Huowuge** [mayooear/gpt4-pdf-chatbot-langchain#166]
Had following the instruction.
Created the pinecone index and named it, use 1536 dimensions, cosine.
However, when I run command: nvm run ingest, it still occurs error as below:
`[WARN] Importing from 'langchain/document_loaders' is deprecated. Import from eg. 'langchain/document_loaders/fs/text' or 'langchain/document_loaders/web/cheerio' instead. See https://js.langchain.com/docs/getting-started/install#updating-from-0052 for upgrade instructions.
....
....
  url: 'https://api.openai.com/v1/embeddings'
  },
  code: 'ERR_NETWORK',
  request: Request {
    [Symbol(realm)]: { settingsObject: [Object] },
    [Symbol(state)]: {
      method: 'POST',
      localURLsOnly: false,
      unsafeRequest: false,
      body: [Object],
      client: [Object],
      reservedClient: null,
      replacesClientId: '',
      window: 'client',
      keepalive: false,
      serviceWorkers: 'all',
      initiator: '',
      destination: '',
      priority: null,
      origin: 'client',
      policyContainer: 'client',
      referrer: 'client',
      referrerPolicy: '',
      mode: 'cors',
      useCORSPreflightFlag: false,
      credentials: 'same-origin',
      useCredentials: false,
      cache: 'default',
      redirect: 'follow',
      integrity: '',
      cryptoGraphicsNonceMetadata: '',
      parserMetadata: '',
      reloadNavigation: false,
      historyNavigation: false,
      userActivation: false,
      taintedOrigin: false,
      redirectCount: 0,
      responseTainting: 'basic',
      preventNoCacheCacheControlHeaderModification: false,
      done: false,
      timingAllowFailed: false,
      headersList: [HeadersList],
      urlList: [Array],
      url: [URL]
    },
    [Symbol(signal)]: AbortSignal { aborted: false },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON],
  attemptNumber: 7,
  retriesLeft: 0
}
/Users/Jeff/ChatGPT/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:44
    throw new Error('Failed to ingest your data');
          ^

Error: Failed to ingest your data
    at run (/Users/Jeff/ChatGPT/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:44:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/Users/Jeff/ChatGPT/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:49:3)` 

I have tried to change node to 18.16.0 and the latest version, not work.

**Comment by mayooear** [comment]
Are you using the latest version of this repo?

**Comment by Huowuge** [comment]
> Are you using the latest version of this repo?

Yes, the latest yarn version.

**Comment by acrons** [comment]
Same error here

**Comment by LorinZhao** [comment]
I got the same error too

**Comment by wpp** [comment]
Do you see something like "429 - Too Many Requests" in the stack trace? Might be https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/42. Try setting up a payment method and creating a new api key.

**Comment by Huowuge** [comment]
> Do you see something like "429 - Too Many Requests" in the stack trace? Might be #42. Try setting up a payment method and creating a new api key.

Have not tried trace that, however I'm a paying user of openai.

**Comment by Kevjinx** [comment]
got the same error too

node -v 18.16, latest repo

**Comment by Kevjinx** [comment]
@Huowuge, ENOTDIR error means that the filepath is looking for a directory, not a path to a file. 

Shoutout to [tuantranf](https://github.com/tuantranf) for posting about this: 
https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/162

I replaced my ingest-data.ts with his, updated the filepath to 'docs/' and load up some pdfs to ingest.

**Comment by Doggson23** [comment]
@Kevjinx, there is no @tuantranf comments in issue #162. Can you please describe in detail how where do you find his ingest-data.ts and how you updated the filepath?

P.S.
I'm a noob in programming...

**Comment by jasredyy5** [comment]
> @Kevjinx, there is no @tuantranf comments in issue #162. Can you please describe in detail how where do you find his ingest-data.ts and how you updated the filepath?
> 
> P.S. I'm a noob in programming...

@Doggson23 , are you able to figure this out? I ran into the exact same issue. Please suggest.

**Comment by LeroyZanzibar** [comment]
I am having the same issue as well. I am not sure @Kevjinx is referring to the correct issue? @mayooear can you help please? I am uploading a single page pdf which I converted to text and back to pdf so it should be ok. I am running Node.js v20.0.0. I am also running ChatGPT v3.5 Turbo and I left it as such in makechain.ts.

**Comment by acshulk** [comment]
Not working for me, and have followed all of the suggestions here.  Does this stack need to update to the latest api as stated in the warnings?

**Comment by bookofbash** [comment]
This is what worked for me.

https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/318#issuecomment-1557525044
