### ISSUE TITLE
Error: PineconeClient: Project name not set. Call init() first.

### ISSUE THREAD

**Issue by yizhanchengyan** [mayooear/gpt4-pdf-chatbot-langchain#172]
hello PINECONE_ENVIRONMENT and PINECONE_INDEX_NAME are same as the pinecone
and I set PINECONE_NAME_SPACE same as PINECONE_INDEX_NAME but it still wrong how to fix it?
thanks

**Comment by bschleter** [comment]
Make sure you make your own .env file and not use env.example. The afterwards, click save to confirm changes or won't work.

**Comment by will2746** [comment]
Yeah I am having the same issue, anyone figure out an answer?
