### ISSUE TITLE
Vercel

### ISSUE THREAD

**Issue by braddaking** [mayooear/gpt4-pdf-chatbot-langchain#175]
When deploying the app it does not read out line by line. It waits and spits out the information. How would I make it so it goes line by line so somebody doesn't think that the app is not responding?

**Comment by bschleter** [comment]
In pages>index.ts file is main editor area for how it looks. From there you'll see the main components of UI is in the other 'components' folder such as 'layout', and 'loading dots'. 

With the base UI, it does shade from gray to wait progressively as it is loading and you'll see other loading features within these files you can adjust.

**Comment by braddaking** [comment]
where specifically in the index?

**Comment by davidhughes3d** [comment]
having the same issue have tried all sorts of fixes no luck
