### ISSUE TITLE
Can Azure OpenAI be integrated?

### ISSUE THREAD

**Issue by youtaya** [mayooear/gpt4-pdf-chatbot-langchain#176]
Is it because langchain's Node.js does not support Azure OpenAI?

**Comment by bschleter** [comment]
Azure cognitive services and separate openAI may be a better and easier to use. 

You can use Azure and OpenAI in langchain as you may know with python, but upon searching Langchains JS documentation I don't see anything for Azure in there. I may have missed though.

**Comment by GitNinja42** [comment]
You need an Azure enterprise account to use it

**Comment by h469705** [comment]
Where should I make the changes to make it work for azure openai? I have the enterprise access
