### ISSUE TITLE
[QUESTION] Replacing newlines with spaces for best results

### ISSUE THREAD

**Issue by atharvashukla** [mayooear/gpt4-pdf-chatbot-langchain#177]
I found this comment in /api/chat here:

https://github.com/mayooear/gpt4-pdf-chatbot-langchain/blob/f1ee996782d107a9a5e4123199a57e008151c2de/pages/api/chat.ts#L25

Where can I find a reference/link to this advice from OpenAI?

**Comment by JWLangford** [comment]
Might a reference here: https://learn.microsoft.com/en-us/azure/cognitive-services/openai/how-to/embeddings?tabs=console
