### ISSUE TITLE
Error ingesting data: Unexpected token A in JSON at position 0

### ISSUE THREAD

**Issue by yaw2014** [mayooear/gpt4-pdf-chatbot-langchain#181]
Trying to ingest some pdfs with Pinecone, and am getting the following error:
`[WARN] Importing from 'langchain/document_loaders' is deprecated. Import from eg. 'langchain/document_loaders/fs/text' or 'langchain/document_loaders/web/cheerio' instead. See https://js.langchain.com/docs/getting-started/install#updating-from-0052 for upgrade instructions.
error [ErrorWithoutStackTrace: PineconeClient: Error getting project name: SyntaxError: Unexpected token A in JSON at position 0]`

Looking online, it seems like previously people were using the wrong format on their .env file. I double checked this and have the following format:
OPENAI_API_KEY= "..."

# Update these with your Supabase details from your project settings > API and dashboard settings
PINECONE_ENVIRONMENT= "us-west1-gcp"
PINECONE_INDEX_NAME= "legal"
PINECONE_API_KEY= "..."

Someone also suggested including the pinecone project name in pinecone-client.ts, but that didn't make a difference.

Any other suggestions? Node.js is up to date.

**Comment by xaviergeorge** [comment]
Similar to this issue  https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/150

**Comment by xaviergeorge** [comment]
Is the pinecone dashboard still in "loading " for you? Could be an issue with the pinecone.
<img width="1400" alt="Screenshot 2023-04-22 at 1 54 51 PM" src="https://user-images.githubusercontent.com/13365640/233783242-c507706f-189b-4636-ab4d-8fc6380edff5.png">

**Comment by Benjamim-EP** [comment]
> Is the pinecone dashboard still in "loading " for you? Could be an issue with the pinecone. <img alt="Screenshot 2023-04-22 at 1 54 51 PM" width="1400" src="https://user-images.githubusercontent.com/13365640/233783242-c507706f-189b-4636-ab4d-8fc6380edff5.png">

for me too, it's giving the error 401

**Comment by oyoops** [comment]
I have the exact same issue but have not gotten a single document to work right.

The only real change I made was to manually add a Docs folder to store PDFs, because, even though I can't find ANYONE else who has noticed this / asked this question, but there is VERY CLEARLY NO "DOCS" FOLDER TO BE FOUND, so not really sure what happened with that in the Readme.  Anyway yeah I can't get this shit to work.

**Comment by yaw2014** [comment]
Just a follow up - my pinecone dashboard indicates that it is ready, so I don't think there's an issue around it still loading (I also paid for pinecone because otherwise I'd be on the waitlist). I have looked at error #150 , and have already included details on the project name in pinecone.ts. That has not made a difference. I guess I will try to uninstall this and run it again? Not sure what other options I have at this point.

**Comment by yaw2014** [comment]
Quick update - I was able to get this to work! I deleted and reloaded the repository, and then also deleted my pinecone index and made a new one. That somehow was enough to get it to function when I ran npm ingest.
