### ISSUE TITLE
Only refers 1 paper though provided multiple PDF

### ISSUE THREAD

**Issue by Holton1** [mayooear/gpt4-pdf-chatbot-langchain#183]
I followed the instruction and the app is deployed. The original app directory doesn't have a folder called "docs" so I created it, and put 4 PDF files in there. When I ask questions, the AI seems can only find results from one PDF. When I run the ingest, I see other PDFs are also ingested. I wonder if anyone else see this issue before?

**Comment by yinshipeng** [comment]
I had the same problem
