### ISSUE TITLE
How to change PINECONE to Chroma

### ISSUE THREAD

**Issue by Sampson91** [mayooear/gpt4-pdf-chatbot-langchain#185]

**Comment by sagarsaija** [comment]
@Sampson91 I made a fork of this repo to change from pinecone to chroma: https://github.com/sagarsaija/gpt4-pdf-chatbot-langchain-chroma

**Comment by davideuler** [comment]
This project has support of docx, pptx, csv, txt, etc. With open source chromadb instread of Pinecone.
[gpt4-pdf-chatbot-langchain-chromadb](https://github.com/davideuler/gpt4-pdf-chatbot-langchain-chromadb)
