### ISSUE TITLE
Is there a way to make it write longer texts?

### ISSUE THREAD

**Issue by thefirst25** [mayooear/gpt4-pdf-chatbot-langchain#189]
it usually only outputs one paragraph, is there a way to make it write a more detailed and longer texts?

**Comment by TychoML** [comment]
You could try and ask for a more elaborate and detailed answer by changing the template in in utils/makechain.ts?

**Comment by groovybits** [comment]
I can control that in my fork by the maxTokens parameter that I am altering like this: https://github.com/groovybits/gaib/blob/main/utils/makechain.ts#L23 Also see how the prompts can provoke more complex / longer answers too. (I have more prompts setup in a config file in my fork you will notice).
