### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by hxsmyxh** [mayooear/gpt4-pdf-chatbot-langchain#190]
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/29764552/233631754-39b649c7-da6b-4306-9687-6275f4a242ca.png">

When i try to let it answer a general question or write 500 words, it 400. Kindly may I know how to fix

**Comment by yinshipeng** [comment]
I had the same problem

**Comment by ryco29** [comment]
I am having this problem as well. When I first ran the build this happened for every question. Then IT worked for a while. Now I'm back to it throwing 400 status.

**Comment by ryco29** [comment]
So I figured out my mistake, and it was a pretty dumb one. I increased my temperature above 1, which you cannot do as 1 is the highest you can go. You can only set the temperature from 0 - 1. Once I set it back to one (or lower) I stopped getting this error and everything worked great. 

<img width="563" alt="Screenshot 2023-05-03 at 9 27 36 PM" src="https://user-images.githubusercontent.com/3358917/236363974-36c74d6e-a823-4762-9bb8-842ada0bcc27.png">

**Comment by wysstartgo** [comment]
I had the same problem

**Comment by karimkawambwa** [comment]
Ran into this, i reduced the chunk size and re ingested the data.

**Comment by mrrobot16** [comment]
@karimkawambwa to which amount exactly you set it up too ?

**Comment by mrrobot16** [comment]
@karimkawambwa Also by chuck size you mean this right? 

<img width="634" alt="Screenshot 2023-06-22 at 12 20 28 PM" src="https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/761735/f472d6f9-6956-44b2-bca4-0fae17bb7707">

**Comment by karimkawambwa** [comment]
@mrrobot16 correct, thats the value I used and I had to create a new api key because i had not setup billing.

**Comment by hunkim98** [comment]
@karimkawambwa What might be an adequate chunkSize value?
