### ISSUE TITLE
Missing value for input

### ISSUE THREAD

**Issue by hyunheung-cho** [mayooear/gpt4-pdf-chatbot-langchain#191]
After I run "npm run dev", I can open up my chat interface at http://localhost:3000

However, it does not answer the question. 
<img width="1499" alt="Screenshot 2023-04-21 at 11 12 03 AM" src="https://user-images.githubusercontent.com/119642243/233672106-6bd03388-e7b1-4723-9737-a3d7067a0970.png">

<img width="1455" alt="Screenshot 2023-04-21 at 11 12 19 AM" src="https://user-images.githubusercontent.com/119642243/233672167-94a09745-d7c1-49ab-b0cb-415a6c2751b8.png">

I attached what I see here.

**Comment by Alvaro97m** [comment]
Although it appears as a string, the names between { } refer to a key that will be called on execution, so to make it work just change it back to 

{context}

Question: {question}
