### ISSUE TITLE
The comment mentions Supabase, but the config is for Pinecone?

### ISSUE THREAD

**Issue by Hesse** [mayooear/gpt4-pdf-chatbot-langchain#198]
https://github.com/mayooear/gpt4-pdf-chatbot-langchain/blob/f1ee996782d107a9a5e4123199a57e008151c2de/.env.example#L3

Just noticed that the comment in the env example mentions Supabase, but the tutorial and code interface with Pinecone DB. Does this mean this code also works with Supabase or is this a artifact from a previous iteration?

**Comment by LunaticProgrammer** [comment]
Yes those comments are wrong I have opened a [MR](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/pull/194) which can fix this bit
