### ISSUE TITLE
Total costs $ for the 56-Page PDF Document vs 1 query

### ISSUE THREAD

**Issue by databill86** [mayooear/gpt4-pdf-chatbot-langchain#20]
Hello,

Could you give us an idea of the total costs for the 56-Page documents given 1 query:
- creating the embedding (a one time step)
- storing the embeddings in Pinecone
- matching a query of 250 tokens vs. the embedding: costs of ADA, and costs of the query to Pinecone
- the first query to gpt4: chat history + the query 
- the second query to gpt4: standalone question + relevant documents

It seems like a lot of queries, it would be very helpful to have an idea about these costs.

Btw, thank you for [this tutorial ](https://www.youtube.com/watch?v=ih9PBGVVOO4)!

**Comment by alfredo-f** [comment]
This is a fantastic idea!

Maybe adding a small counter of dollars spent in the front-end can save you from a heart attack when the credit card bill rolls in

**Comment by kimjongbing** [comment]
Also curious about this! Not sure how much money I'd burn through if I used this.

**Comment by mayooear** [comment]
Embeddings cost $0.0004 / 1K tokens so they are very cost-effective. (1 token is approx 3/4 words)
Using openai's (tokenizer)[https://platform.openai.com/tokenizer?view=bpe], you can see how tokens are calculated.
For example, if you're embedding 50-page PDF that's approx 25,000 words. Which is approx. 33,000 tokens ~ $ 0.001

For context, it costs approx 0.48 USD per 1.2 million tokens embeddings.

With respect to pinecone pricing, the free tier is very generous, but for paid/production level pricing is [here](https://www.pinecone.io/pricing/)

As for the gpt-4 calls, I will continue to review the intermediate steps and get back on that shortly.

**Comment by sebastienfi** [comment]
About Pinecone pricing, it would be possible to switch to [pgvector](https://github.com/pgvector/pgvector) for a self-hosting.

**Comment by databill86** [comment]
> About Pinecone pricing, it would be possible to switch to [pgvector](https://github.com/pgvector/pgvector) for a self-hosting.
I think there are a [good number of alternatives](https://github.com/openai/chatgpt-retrieval-plugin/tree/main#choosing-a-vector-database) referenced by OpenAI in the chatgot retrieval plugin repository. 
I wonder if it's possible to plug [weaviate](https://weaviate.io/) in here.
