### ISSUE TITLE
Error initializing pinecone client

### ISSUE THREAD

**Issue by jshalabi03** [mayooear/gpt4-pdf-chatbot-langchain#200]
I setup a Pinecone account and retrieved the API key and environment name from the Pinecone default project. I have not done anything else on the Pinecone console, so I specified `PINECONE_INDEX_NAME` to be an arbitrary name. Running `npm ingest`produced the following output,

`> gpt4-langchain-pdf-chatbot@0.1.0 ingest
> tsx -r dotenv/config scripts/ingest-data.ts

[WARN] Importing from 'langchain/document_loaders' is deprecated. Import from eg. 'langchain/document_loaders/fs/text' or 'langchain/document_loaders/web/cheerio' instead. See https://js.langchain.com/docs/getting-started/install#updating-from-0052 for upgrade instructions.
error [ErrorWithoutStackTrace: PineconeClient: Error getting project name: SyntaxError: Unexpected token 'A', "API key is"... is not valid JSON]
/Users/jshalabi/dev/projects/repos/gpt4-pdf-chatbot-langchain-main/utils/pinecone-client.ts:19
    throw new Error('Failed to initialize Pinecone Client');
          ^

Error: Failed to initialize Pinecone Client
    at initPinecone (/Users/jshalabi/dev/projects/repos/gpt4-pdf-chatbot-langchain-main/utils/pinecone-client.ts:19:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/Users/jshalabi/dev/projects/repos/gpt4-pdf-chatbot-langchain-main/utils/pinecone-client.ts:23:25)

Node.js v19.7.0`

The environment variables are being exposed correctly.

**Comment by simonszalai** [comment]
I had the same error. The problem was that the environment variables were not loaded. You can fix it by adding these 2 lines:

```
import dotenv from 'dotenv';
dotenv.config();
```

To the `ingest-data.ts` file

**Comment by OdinM13** [comment]
> 

does not work

**Comment by OmiWakode** [comment]
I have the same issue! Did anyone solve this?

**Comment by ratiarsone** [comment]
I have the same issue. pls help

**Comment by Iamtheoldman** [comment]
Anyone found a workaround
