### ISSUE TITLE
FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by AZero712** [mayooear/gpt4-pdf-chatbot-langchain#201]
I pulled the node:20.0.0-slim image in docker hub and ran the project in a container that used that image.
When I run npm run ingest, the following error message appears 
![image](https://user-images.githubusercontent.com/79622002/233817717-c7e49adb-53f4-46bd-9b5f-0929bfd69539.png)

**Comment by davidfrothin** [comment]
same issue with a text file too

**Comment by davidfrothin** [comment]
i had the same issue with total 7000+ vectors. I deleted some data to 2000+ vectors and it worked fine. It will be useful to find solution to load more data.
