### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by billyjingxuan** [mayooear/gpt4-pdf-chatbot-langchain#206]
Always show the below error after run the ingest command. I double check all the data input in the config file and env file, all correct. Anyone can support? Thanks.
creating vector store...
error Error: Network Error
    at createError (file:///C:/Users/aa/Downloads/gpt4-pdf-chatbot-langchain-main/node_modules/langchain/dist/util/axios-fetch-adapter.js:312:19)
    at getResponse (file:///C:/Users/aa/Downloads/gpt4-pdf-chatbot-langchain-main/node_modules/langchain/dist/util/axios-fetch-adapter.js:189:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchAdapter (file:///C:/Users/aa/Downloads/gpt4-pdf-chatbot-langchain-main/node_modules/langchain/dist/util/axios-fetch-adapter.js:166:18)
    at RetryOperation._fn (c:\Users\aa\Downloads\gpt4-pdf-chatbot-langchain-main\node_modules\p-retry\index.js:50:12) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [AsyncFunction: fetchAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.2.1',

**Comment by Hesse** [comment]
@billyjingxuan try deleting and re-creating your index and in a different region. I had a similar issue however after re-creating my index in Canada it worked. I'm sure the US will work as well. It was originally failing because my index was in Asia.

**Comment by elseswitch** [comment]
> @billyjingxuan try deleting and re-creating your index and in a different region. I had a similar issue however after re-creating my index in Canada it worked. I'm sure the US will work as well. It was originally failing because my index was in Asia.

hi，i have a same issue. 
What does 'index' mean here?
thanks

**Comment by Hesse** [comment]
> > @billyjingxuan try deleting and re-creating your index and in a different region. I had a similar issue however after re-creating my index in Canada it worked. I'm sure the US will work as well. It was originally failing because my index was in Asia.
> 
> hi，i have a same issue. What does 'index' mean here? thanks

In Pinecone, you create an index.

**Comment by elseswitch** [comment]
> 



> > > @billyjingxuan try deleting and re-creating your index and in a different region. I had a similar issue however after re-creating my index in Canada it worked. I'm sure the US will work as well. It was originally failing because my index was in Asia.
> > 
> > 
> > hi，i have a same issue. What does 'index' mean here? thanks
> 
> In Pinecone, you create an index.

thanks ,iam not using pinpone. the issue occurs when accessing the openai interface

**Comment by KowComical** [comment]
same issue for me:(
