### ISSUE TITLE
Integrating metadata into the vector store

### ISSUE THREAD

**Issue by disturbed-mystic1** [mayooear/gpt4-pdf-chatbot-langchain#215]
Is there a way to store the metadata (heading of a pdf) in the vector store and direct the chatbot to provide key findings or questions based on that? Has it been implemented in the code if not, does anyone have a solution?

**Comment by report2model** [comment]
I was interested in the same thing. I have gotten multiple pdfs to be referenced in one query, but it requires a minimum number of references (seems to be about 6-10 for an 12k vector index). With the increased references the response time increases as well, leading to long wait times. It seems like if metadata could be added to the vector store then you could speed the process back up without the need of increasing references potentially.

**Comment by toddbomb** [comment]
Bump on this! I'm working with pdfs that need the author's name to be stored with each vector so I can ask the LLM who wrote what. Is there a way to do this that isn't just having the each full pdf page to be stored seperately?

**Comment by ashokrs** [comment]
Folks,
I had the same problem. I cheated by grabbing name:value pairs of the entire “metadata” content and slapped in the body of the document to get them into the vector store.  I could put the metadata in an external system and father edit like SharePoint’s term Store and reference each pdf document that way which is a cumbersome approach but my propspect prefers it that way. Looking for more formal way to make the chatbot or LLM conversation chain to recognize the info coming from metadata. Anything else looks like a hack to promote metadata.

**Comment by arieefrachman** [comment]
yeah, we have same problem on this

**Comment by linchen111** [comment]
mark，we have same problem on this
