### ISSUE TITLE
error Error: connect ECONNREFUSED ::1:8000 (Chroma)

### ISSUE THREAD

**Issue by anant2614** [mayooear/gpt4-pdf-chatbot-langchain#222]
I'm running the Chroma docker image on Mac and I guess IPV6 support is not yet enabled. The image is up and running and reachable on 127.0.0.1:8000. Is there any way to override the host to use IPV4 ?

Full error:

`error Error: connect ECONNREFUSED ::1:8000
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:668:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 8000,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },`

**Comment by chase-crumbaugh** [comment]
Also running into this. Any chance you found a workaround?

**Comment by Kheurt** [comment]
Got the same error... anyone solved it?

**Comment by BK-beep** [comment]
got the same error

**Comment by dsws** [comment]
Any solutions to this?

**Comment by rahulsushilsharma** [comment]
I was getting the same error but I was running the chroma client on local (not docker) with 
```sh 
chroma run --path ./db
```

I tried to change the path in the `ChromaClient` constructor to this and it works.
```ts
const client = new ChromaClient({
    path:"http://127.0.0.1:8000",
    
});
```

I don't know why I was getting this error as it was working fine when I was using docker but not on my local, tho I was getting a heartbeat for both of the causes...
