### ISSUE TITLE
Error: Failed to initialize Pinecone Client

### ISSUE THREAD

**Issue by ViniciusTheCoder** [mayooear/gpt4-pdf-chatbot-langchain#226]
I'm having this error when running **`npm run ingest`**. I don't know what I'm doing wrong, here's a screenshot of how my ingest-data.ts and pinecone.ts are configured. I saw in another issue that to solve this problem it was enough to add 
```
import dotenv from 'dotenv'; 
dotenv.config();
```
 to the ingest-data.ts file. I tried to do that but it didn't work:

Error: Failed to initialize Pinecone Client
    at initPinecone (c:\Users\admin\Documents\gpt4-pdf-chatbot-langchain\utils\pinecone-client.ts:19:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (c:\Users\admin\Documents\gpt4-pdf-chatbot-langchain\utils\pinecone-client.ts:23:25)

My ingest-data.ts 
![image](https://user-images.githubusercontent.com/100241274/235030488-d019659f-ac05-489f-875a-f4808d9dad66.png)
My pinecone.ts 
![image](https://user-images.githubusercontent.com/100241274/235030558-0d396905-ee4b-4e0a-962e-54e5179ec5fe.png)

My API Keys, Index Name and Envinroment are correct at .env file

My current repo https://github.com/ViniciusTheCoder/GPT_PDF

**Comment by pushkarlakhe13** [comment]
I have the same error. My key, index name and environment are correct

**Comment by ViniciusTheCoder** [comment]
@pushkarlakhe13 so, yesterday I cloned the repo, followed exactly the same steps and it worked. I guess that maybe the node version can impact directly the final result

**Comment by ChristianEvc** [comment]
Hi @ViniciusTheCoder . Which Node version are you on? I'm having the same issue, and I'm on Node v18.16.0.
