### ISSUE TITLE
Increase answering speed of chatbot?

### ISSUE THREAD

**Issue by tifa365** [mayooear/gpt4-pdf-chatbot-langchain#230]
Firstly, I want to say thanks to Mayo for making this chatbot open source. I have noticed that the chatbot takes a significant amount of time to load before answering my queries. In contrast, I have previously used a similar bot built in Langchain using Python, which answered instantly. As I am using GPT-3.5, I was wondering if there are any tips on how to optimize the speed of the chatbot?

**Comment by VladislavKatsubo** [comment]
@tifa365 Hello. I am experiencing the same problem. It takes around 1-3 minutes from time to time, to wait for response. Have you found a solution?
