### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by superali10** [mayooear/gpt4-pdf-chatbot-langchain#231]
when I run the above command I get 

> gpt4-langchain-pdf-chatbot@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/superali/gpt4-pdf-chatbot-langchain/.env
event - compiled client and server successfully in 861 ms (173 modules)
wait  - compiling...
event - compiled successfully in 67 ms (139 modules)

but nothing else happens
I get the same issue on Windows and Linux
I assume it is my setup but there are no error messages

**Comment by Beskaar** [comment]
url: http://localhost:3000 ?

**Comment by davidhughes3d** [comment]
bruh, click the url....

**Comment by superali10** [comment]
thanks for the heads up
the pdf files, I've tried, ingest OK and the browser redirects to localhost:3000 OK
but the touchdown page in the browser is **Chat With Your Legal Docs**
any queries I submit get the error **Request failed with status code 404**
any help is appreciated

**Comment by rashidy14** [comment]
> managed to figure it. thanks.

I have the same Issue. How did you manage to do it?

**Comment by RazeBerry** [comment]
> > managed to figure it. thanks.
> 
> I have the same Issue. How did you manage to do it?

You literally put " localhost:3000" into the browser

**Comment by pinballelectronica** [comment]
I think he's saying he's getting 404's after asking a question in the window.

**Comment by superali10** [comment]
put " localhost:3000" into the browser or click the link in your terminal

and

I had to change the modelname in makechain.ts to

modelName: 'gpt-3.5-turbo',    //change this to gpt-4 if you have access

I'm not signed up to the gpt-4 api.
