### ISSUE TITLE
About changing the number of sources

### ISSUE THREAD

**Issue by FHL1998** [mayooear/gpt4-pdf-chatbot-langchain#234]
How to change the number of sources in makechian.ts?
The current code just illustrate the default value: 
`returnSourceDocuments: true, //The number of source documents returned is 4 by default`

**Comment by marc76900** [comment]
> How to change the number of sources in makechian.ts? The current code just illustrate the default value: `returnSourceDocuments: true, //The number of source documents returned is 4 by default`

Have you find how to modify it ?
