### ISSUE TITLE
Vercel returns "An error occurred while fetching the data. Please try again."

### ISSUE THREAD

**Issue by frederikskovw** [mayooear/gpt4-pdf-chatbot-langchain#238]
Sorry for this noob question, but could not see an answer anywhere else, so thought there might be others with the same problem.

My project works locally, but when hosted in Vercel it returns "An error occurred while fetching the data. Please try again.".

How come?

**Comment by frederikskovw** [comment]
solved - missed rebuild after adding env variables

**Comment by P-hongsi** [comment]
can u show me code? im same problem with u
