### ISSUE TITLE
Rewriting in Python

### ISSUE THREAD

**Issue by FHL1998** [mayooear/gpt4-pdf-chatbot-langchain#244]
Really impressive work! I am a Python guy, is anyone interested in rewriting this project in Python?

**Comment by ldtownsend** [comment]
I'm interested and and want to start tonight. But without an MIT or Apache license posted I'm a little hesitant to post it when done.

**Comment by ThomasEwing04** [comment]
> I'm interested and and want to start tonight. But without an MIT or Apache license posted I'm a little hesitant to post it when done.

This.

**Comment by PhilipAD** [comment]
Uses a [ConversationalRetrievalQAChain](https://js.langchain.com/docs/modules/chains/index_related_chains/conversational_retrieval) which I think is the equivalent of [ConversationalRetrievalChain](https://python.langchain.com/en/latest/modules/chains/index_examples/chat_vector_db.html).

[import { PineconeStore } from 'langchain/vectorstores/pinecone';
import { ConversationalRetrievalQAChain } from 'langchain/chains';](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/blob/main/utils/makechain.ts)

`ConversationalRetrievalChain.from_llm(llm, docsearch.as_retriever(), memory=memory, condense_question_prompt=PROMPT, return_source_documents=True)`

Although, the answers I get back are much shorter. I'm assuming the underlying implementation ConversationalRetrievalQAChain is different?

**Comment by drewskidang** [comment]
some one please try this

**Comment by Lukas-Novak** [comment]
It is a bit different project, but Zak Elmeghni already provided a tutorial how to do it in python: https://blog.nextideatech.com/chat-with-documents-using-langchain-gpt-4-python/

**Comment by drewskidang** [comment]
homie!!

**Comment by BahaEddineD** [comment]
can some one give me the code in python guys i need it so bad

**Comment by drewskidang** [comment]
@BahaEddineD heres the ingest method of it

https://github.com/ucl98/pinecone_ingest_python_implementation

you can take a look at https://github.com/Chainlit/cookbook for examples

**Comment by VigneshDevelops** [comment]
Check this out for Python implementation 
https://github.com/VigneshDevelops/chat-with-docs
