### ISSUE TITLE
Igesting 'tsx' is not recognized 

### ISSUE THREAD

**Issue by Bosideburns** [mayooear/gpt4-pdf-chatbot-langchain#249]
Seems to be having an error when ingesting here is the code that I am running along with the output.
INPUT:

PS C:\Users\burnsidet\Documents\gpt4-pdf-chatbot-langchain-main> npm run ingest

OUTPUT:

> gpt4-langchain-pdf-chatbot@0.1.0 ingest    
> tsx -r dotenv/config scripts/ingest-data.ts

'tsx' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\burnsidet\Documents\gpt4-pdf-chatbot-langchain-main>

**Comment by Bosideburns** [comment]
Yes, I have but, I see my issue because I never ran yarn install because I am attempting to build this out on my school computer they have disabled running scripts on this system if you have any ideas about potential workarounds about how to work around this feel free to let me know.

**Comment by Bosideburns** [comment]
After looking into things a bit further this was not a school-imposed restriction but a PowerShell default setting that seemed to be set by default by my administration. The following link talks about this https:/go.microsoft.com/fwlink/?LinkID=135170
though to save some time if others run into similar issues with their PowerShell follow the next steps.
1) Open PowerShell and run as administrator
2) Run `Set-ExecutionPolicy -ExecutionPolicy Unrestricted` 
3) Check that you now have by running `Get-ExecutionPolicy` 

Hopefully, this helps

**Comment by Sine-Of-Time** [comment]
I had to make sure I had langchain installed and also used VScode to fix some other import errors related to the process object.

**Comment by larri-eng** [comment]
I am getting the same issue. Any assistance is appreciated

ExecutionPolicy is "AllSigned"


![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/67224556/9359af1f-6631-4092-9948-ced28c1f1da6)

**Comment by cappelletto** [comment]
@larri-eng try installing the missing **tsx** dependency using
`npm install tsx`
