### ISSUE TITLE
Live Deployment Issues

### ISSUE THREAD

**Issue by darkomking** [mayooear/gpt4-pdf-chatbot-langchain#25]
I'm having a couple of issues with a live deployment to Vercel that I don't have in the local environment. Requests are often ending with ```An error occurred with your deployment FUNCTION_INVOCATION_TIMEOUT```. Looking in the Vercel function logs you can actually see responses are getting created, but just ending in a 504. Additionally when the request is returned successfully there is no live text printout, the answer just shows up when completed. Everything works well in the local environment however. Anyone else experiencing this?

![image](https://user-images.githubusercontent.com/1041446/226996188-eed51e44-bab7-45ad-b3ed-84e90d2f2b40.png)

**Comment by mayooear** [comment]
"If the Serverless Function does not respond to the HTTP request within the timeout, then a 504 error status code is returned with the error code [FUNCTION_INVOCATION_TIMEOUT](https://vercel.com/docs/error/application/FUNCTION_INVOCATION_TIMEOUT)."

Vercel has a serverless function timeout of approx. 10 seconds on the hobby plan: [docs](https://vercel.com/docs/concepts/limits/overview)

Options would be either to try the Pro version, or other deployment platforms.

**Comment by rgsaura** [comment]
@darkomking Hey! What platform did you end up using. Im looking for one!

**Comment by rgsaura** [comment]
Did you change something in settings? I upgraded but the 10 sec limit still there

**Comment by felipeotarola** [comment]
> Did you change something in settings? I upgraded but the 10 sec limit still there

You need to redeploy before this takes effect  👍
