### ISSUE TITLE
Differences to chatpdf.com

### ISSUE THREAD

**Issue by thomasklein** [mayooear/gpt4-pdf-chatbot-langchain#256]
Hi! I noticed chatpdf.com seems to take a different approach when it comes to the ingestion of a pdf document. E.g. chatpdf is "aware" that it works on a pdf document with pages and sections - so I can ask it on which page it found information or to summarise certain sections. 

So, for high level questions I think this project and chatpdf.com are comparable. However, diving into details of a document chatpdf.com feels to me more accurate which is curious as both use in the end the same LLMs in the backend.

Has anyone a guess what can be improved in the technology stack of this project to come closer to chatpdf results?

**Comment by pitieu** [comment]
Accuracy depends on how you store chunks in the vector store and how you process it once you retrieve it.
If chunks are small you will get a more granular match. If too small then it might not match well enough, you have to find the right balance. Using overlap can help accuracy. 

Once you retrieve the chunks you always have the option to let it go through the LLM again which is maybe what they are doing to get a better detailed explanation to match the user prompt.

Another idea i had was what if when you're splitting into chunks you would chunk them as paragraphs and run those paragraphs through an LLM to expand it in more detail with more knowledge and only then you store it. This would depend on the use case obviously but it can help with accuracy.
