### ISSUE TITLE
Use "npm run ingest" to upload the pdf file is incomplete

### ISSUE THREAD

**Issue by yaya6630170** [mayooear/gpt4-pdf-chatbot-langchain#258]
I tried two pdf files and both are incomplete, only a small part of the file. It is uploaded successfully, but for example a book on C#, there are only three small paragraphs, causing GPT not to know that it is a book on C#.

**Comment by ucl98** [comment]
You could try https://github.com/ucl98/pinecone_ingest_python_implementation.
Might work and easier to debug

**Comment by yaya6630170** [comment]
> 
I can't use this，report“Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 8.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)'))).”
I use "gpt4-pdf-chatbot-langchain"  with clash's TUN mode, which can upload the pdf file, but the document is incomplete

**Comment by yaya6630170** [comment]
> You could try https://github.com/ucl98/pinecone_ingest_python_implementation. Might work and easier to debug

I can't use this，report“Retrying langchain.embeddings.openai.embed_with_retry.._embed_with_retry in 8.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)'))).”
I use "gpt4-pdf-chatbot-langchain" with clash's TUN mode, which can upload the pdf file, but the document is incomplete

**Comment by yaya6630170** [comment]
Obviously, It's a problem with the network connection, but I can't solve it very well.  T   T

**Comment by ucl98** [comment]
You may go to openai, check your account, go to playground and see if you can send messages.
My guess would be a problem with your account. Maybe you reached your limit, maybe you have not activated it correctly...
