### ISSUE TITLE
new issue with pinecone now - any idea how to solve?

### ISSUE THREAD

**Issue by rossman22590** [mayooear/gpt4-pdf-chatbot-langchain#26]
us-east1-gcp
PineconeClient: Error getting project name: FetchError: invalid json response body at https://controller.us-east1-gcp.pinecone.io/actions/whoami reason: Unexpected token A in JSON at position 0
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}

**Comment by rossman22590** [comment]
ok i solved this in the code by adding my name

**Comment by mayooear** [comment]
Where did you add your name? Please share your solution for future users.

**Comment by rossman22590** [comment]
Head to Pinecone.ts and input your name properly.

**Comment by ac1982** [comment]
> Head to Pinecone.ts and input your name properly.

Could you please provide me with more information on how to solve this problem? I had config the ```config/pinecone.ts``` and set both ```const PINECONE_INDEX_NAME = "my_value"``` and ```const PINECONE_NAME_SPACE = "my_another_value";``` . However, I am still receiving the error message:  ```error - [Error: PineconeClient: Project name not set. Call init() first.] ``` .
