### ISSUE TITLE
local free models and DB

### ISSUE THREAD

**Issue by HananInfiniGrow** [mayooear/gpt4-pdf-chatbot-langchain#260]
Hi,
Exactly what I need but I want to run locally without API calls due to document privacy issues.
What are the steps to do that? What kind of models I can download which will work with this?
Same for DB rather than using Pinecone

**Comment by aktary** [comment]
Chroma instead of Pinecone
Depending on your licensing (and other) needs, you could consider MosaicML's MPT that they just released.

**Comment by madruga8** [comment]
theres a tutorial that connects with chromadb ?

**Comment by davideuler** [comment]
Chromadb instread of Pinecone as this project: 
[gpt4-pdf-chatbot-langchain-chromadb](https://github.com/davideuler/gpt4-pdf-chatbot-langchain-chromadb)
