### ISSUE TITLE
npm run ingest error

### ISSUE THREAD

**Issue by MaxMaker627** [mayooear/gpt4-pdf-chatbot-langchain#261]
Hello, i'm having this problem:

```
c:\Users\Miguel\Desktop\gpt4-pdf-chatbot-langchain-main\scripts\ingest-data.ts:44
    throw new Error('Failed to ingest your data');
          ^
Error: Failed to ingest your data
    at run (c:\Users\Miguel\Desktop\gpt4-pdf-chatbot-langchain-main\scripts\ingest-data.ts:44:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (c:\Users\Miguel\Desktop\gpt4-pdf-chatbot-langchain-main\scripts\ingest-data.ts:49:3)

Node.js v18.16.0
```

I think that I have a bad pinecone configuration. Please, help me

**Comment by normaescobar** [comment]
I am encountering this same erro. Can someone please provide some context? For reference, temp is set to 0, pdf is not corrupted and/or my api key has access to gpt4.
![Uploading IMG_6681.png…]()

**Comment by MaxMaker627** [comment]
You need to have an openai paíd account

**Comment by ljs19923** [comment]
Same error. My openai account is a paid one. @normaescobar did you find a solution?

**Comment by normaescobar** [comment]
@ljs19923 yes I was able to find my issue. Look for a cases I closed a couple of days ago! I wrote the response there!! But in short, all we have to do is change the version of yarn
