### ISSUE TITLE
An error occurred while fetching the data

### ISSUE THREAD

**Issue by frank0828** [mayooear/gpt4-pdf-chatbot-langchain#264]
I finally got the Vectors to store on Pinecone, but when I try to run it locally, I got " An error occurred while fetching the data. Please try again." , when I send a message. Please help me.

error [ErrorWithoutStackTrace: PineconeClient: Error getting project name: SyntaxError: Unexpected token A in JSON at position 0]
error - utils\pinecone-client.ts (19:10) @ initPinecone
error - Error: Failed to initialize Pinecone Client
    at initPinecone (webpack-internal:///(api)/./utils/pinecone-client.ts:23:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(api)/./utils/pinecone-client.ts:26:18)
  17 |   } catch (error) {
  18 |     console.log('error', error);
> 19 |     throw new Error('Failed to initialize Pinecone Client');

![de871cffa93bcddf613fd5394827d7c](https://user-images.githubusercontent.com/62916798/236889753-d1b6b887-eeee-4a21-a1f8-7bd1dbdeb74d.png)

**Comment by dissorial** [comment]
Looks like your pinecone is not configured properly. Are your pinecone index and api keys set correctly in the env file?
