### ISSUE TITLE
'Failed to ingest your data' after npm run ingest

### ISSUE THREAD

**Issue by normaescobar** [mayooear/gpt4-pdf-chatbot-langchain#271]
Hello everyone,

For context: I have a paid OpenAI account, the temp is set to 0 and my index on Pinecone is running fine.

This is the error message I get:

```
c:\Users\remoteWorkPC\Desktop\chat-with-data\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:44
    throw new Error('Failed to ingest your data');
          ^


Error: Failed to ingest your data
    at run (c:\Users\remoteWorkPC\Desktop\chat-with-data\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:44:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (c:\Users\remoteWorkPC\Desktop\chat-with-data\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:49:3)

Node.js v18.15.0
```

The feedback that I have gotten is that I need a paid account on OpenAI in order to avoid this error. I already have a paid account and my efforts have been to no avail.

Is someone also encountering the same issue that could provide some insight?

**Comment by normaescobar** [comment]
Should also point out that the pdf file I am using is not corrupted.

**Comment by normaescobar** [comment]
Alright, I finally know what went wrong:

A couple of weeks ago I set a specific environment variable that pointed to a different API key (which I had already deleted on my Open AI account, but had not removed the variable from the environment).

If you are on Windows just go to advanced system settings>edit environment variables and make sure there is nothing under "OPEN_AI."

I the error persists, try this:

In your terminal type `corepack enable` nothing happens here besides taking you to a new line.
In your terminal type `corepack prepare yarn@stable --activate`
In your terminal type `yarn set version stable`
In your terminal type `yarn -v` and now you should see 3.5.0

Now you follow along with the readme and by running: yarn install

**Comment by ljs19923** [comment]
So your problem was about Open AI API key? I have the same error and my openAI api key is the good one
