### ISSUE TITLE
如何修改api.openai.com请求地址，我需要通过代理访问api.openai.com

### ISSUE THREAD

**Issue by liuyang77886** [mayooear/gpt4-pdf-chatbot-langchain#273]
在工程代码里没有找到api.openai.com请求地址和请求代码，请问在哪里修改api.openai.com为我的代理地址？

**Comment by LogicalMonster** [comment]
我自己试了一下发现可以这样更改，先在根目录运行npm install yarn -g和yarn install这两条命令，等到node_modules文件夹下载完成后，将gpt4-pdf-chatbot-langchain\node_modules\openai\base.ts和gpt4-pdf-chatbot-langchain\node_modules\openai\dist\base.js这两个文件中的出现的api.openai.com更改为你自己的代理地址就可以了。这样改运行时会有警告但是可以使用。更改中文回答的话，还有这个教程https://www.bilibili.com/read/cv22589352?spm_id_from=333.999.0.0
I tried it myself and found that it can be modified in this way. First, run the commands 'npm install yarn -g' and 'yarn install' in the root directory. After the node_modules folder is downloaded, change the occurrence of 'api.openai.com' in the two files 'gpt4-pdf-chatbot-langchain\node_modules\openai\base.ts' and 'gpt4-pdf-chatbot-langchain\node_modules\openai\dist\base.js' to your own proxy address. Although this change will trigger warnings during operation, it is usable. As for changing the Chinese response, there is also this tutorial: https://www.bilibili.com/read/cv22589352?spm_id_from=333.999.0.0.

**Comment by Shadow-Alex** [comment]
如果你用的是 clash，请开启 service mode，并开启 TUN Mode，并使用system：
这个配置将接管绝大多数网络流量，即便它们没有明令设置代理 
If you are using clash, please activate service mode & enable TUN mode, and use 'system' as TUN stack.
This setup will takeover your web traffic. Even if they are not setup for proxy :)

![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/46802674/b30ca5d0-b6a1-4d99-a068-6f7a42f58acf)
![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/46802674/c6de9095-a0b2-4fef-9ba4-7b6d31135c59)

**Comment by MorenMoren** [comment]
如果你需要利用反向代理，那你可以在所有需要调用new openai或者new openai embeddings的地方更改basePath。
详细信息参考：https://github.com/hwchase17/langchainjs/issues/388

**Comment by zjm168love** [comment]
如果是正向代理怎么配置呢，系统的代理完全被忽略了，

**Comment by nGkp5E76** [comment]
> 如果是正向代理怎么配置呢，系统的代理完全被忽略了，

@zjm168love 
上面的回答已经说的很清楚了，可以设置tunel mode。
你还可以参考一下这个链接
 [Nodejs和python 设置 openai 的API正向代理和反向代理入口链接连接方式，用于国内访问openAI接口_python 反向代理-CSDN博客]( https://blog.csdn.net/qq_36265860/article/details/130111351 )

**Comment by Tilie** [comment]
我找到了一个方案暂时未测试。
https://github.com/openai/openai-node/issues/85

如果本项目调用的是这个包来调用openai的api的话，按照上面的方法应该能上

I found a solution that I haven't tested yet. 
https://github.com/openai/openai-node/issues/85

If this project uses this package to call the openai API, following the method above should allow for proxy setup.
