### ISSUE TITLE
Free Vector Database?

### ISSUE THREAD

**Issue by fading-bit** [mayooear/gpt4-pdf-chatbot-langchain#274]
Hi. I have used an integration of langchain with Pinecone, as well as ChromaDB. My question is whether you recommend any alternative vector database that is free?

**Comment by davideuler** [comment]
This fork is based on open source chromadb instread of Pinecone. with support of docx, pptx, csv, txt, etc. 
[gpt4-pdf-chatbot-langchain-chromadb](https://github.com/davideuler/gpt4-pdf-chatbot-langchain-chromadb)
