### ISSUE TITLE
Does this css support large screens?

### ISSUE THREAD

**Issue by rossman22590** [mayooear/gpt4-pdf-chatbot-langchain#28]
When screen is large its sits to the left of the screen any idea where to fix this css?

**Comment by mayooear** [comment]
It's working fine on my end. Can you send screenshot? What browser are you using

**Comment by rossman22590** [comment]
im using chrome , this css seems to fix it but idk where to put it ..

.container {
    max-width: 100%;}


![screenshot-gpt4-pdf-chatbot-langchain-production up railway app-2023 03 23-11_58_07](https://user-images.githubusercontent.com/6137292/227262539-364bbe53-5216-4e45-81db-8d4abeba340c.png)

**Comment by mayooear** [comment]
Is this resolved?

**Comment by rossman22590** [comment]
did you update main with a fix?

**Comment by rossman22590** [comment]
i have redeployed and same result

**Comment by mayooear** [comment]
I will look to fix this in the next PR. Although it seems to be an issue once deployed?
