### ISSUE TITLE
env file

### ISSUE THREAD

**Issue by jmayank23** [mayooear/gpt4-pdf-chatbot-langchain#282]
After git clone and yarn install, I have a folder with gpt4-pdf-chatbot-langchain, node_modules and yarn.lock

1. Where do I need to place the .env file
2. Are all API keys, pinecone env name and index name supposed to be entered in single quotes or as is?
KEY='key'
or
KEY=key

**Comment by dmperdue** [comment]
Place the .env in the root of the folder.

Add the keys, environment, index_name as is; e.g. KEY=key.

I was getting ingest errors and removing the quotes from the .env values fixed it.

**Comment by dissorial** [comment]
All variables are without quotes

**Comment by GTG101** [comment]
> Place the .env in the root of the folder.
> 
> Add the keys, environment, index_name as is; e.g. KEY=key.
> 
> I was getting ingest errors and removing the quotes from the .env values fixed it.

The root of what folder?
