### ISSUE TITLE
npm ERR! Missing script: "ingest"

### ISSUE THREAD

**Issue by bert2345678** [mayooear/gpt4-pdf-chatbot-langchain#285]
Hi, I am trying to run the ingest but run into the following message.

npm ERR! Missing script: "ingest"

I don't really understand where the error can come from. What I notice is that when I go to ingest-data.ts I get 5 error messages. 

Cannot find module 'langchain/text_splitter' or its corresponding type declarations

I have langchain installed. When I do this again I get the message requirements already satisfied.

I have added to my environment variable: C:\Users\XXX\anaconda3\Lib\site-packages\langchain

When I run npm install langchain/text_splitter I get the message that the npm not being able to find a file

This is my first time delving into programming. 

Can anyone help me?

Thanks

**Comment by dissorial** [comment]
Did you use yarn or npm when setting up the project?

**Comment by bert2345678** [comment]
Thank you for your response. 

When I run yarn version check via cmd I get the message:

Warning package.json: No license field
Error use the new version flag to create a new version

When i run yarn install 
I got a warning your project contains lock files generated by tools other then yarn 

When i run npm install i got the massage up to date audited 2 packages in 500ms

I think I'm doing something wrong here. What is the best thing to do as a next step?

Thankyou

**Comment by dissorial** [comment]
Try to delete the entire repo and do this installation/setup process again, but now with yarn.
