### ISSUE TITLE
Increase the number of sources 

### ISSUE THREAD

**Issue by simon555** [mayooear/gpt4-pdf-chatbot-langchain#291]
Hi ! :) 

Where in the code can you increase the number of sources to retrieve ?

Thanks!

**Comment by dissorial** [comment]
It was possible to do that with older versions of langchain, but there doesn't seem to be a way to do that with the newest one.

**Comment by andreifoldes** [comment]
Yes, this would very useful to modify as a parameter...

**Comment by ZackAllen1** [comment]
Sorry for the late response, I was able to change the number of sources to retrieve by modifying the following code in `makechain.ts`

```typescript
const chain = ConversationalRetrievalQAChain.fromLLM(
    model,
    vectorstore.asRetriever(8), // setting the number of source documents to 8
    {
      qaTemplate: QA_PROMPT,
      questionGeneratorTemplate: CONDENSE_PROMPT,
      returnSourceDocuments: true,
    },
  );
```

**Comment by rodneysdf** [comment]
I found 22 was the maximum for this chain and my documents.
