### ISSUE TITLE
Project is not working well and wanna know the reason.

### ISSUE THREAD

**Issue by melody4482** [mayooear/gpt4-pdf-chatbot-langchain#297]
Hi, thanks for making this project.
I wanna build my own chatbot based on this project but this is not working well on my side.
Of course there's no syntax error.
But please put your eyes on these pictures.
![Screenshot_1](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/125443259/5d68b342-488d-4db7-87e1-7d6944810aaa)

I provided this PDF file.
[Test.pdf](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/files/11489357/Test.pdf)

These are my testing answers

1. Can you explain the article in 10 bullet points?
2. Can you list the the key findings?
3. Can you list the possible real-world implications for the business and tech industry
4. What industries would this research have potentially practical applications?
5. Can you write a short background on the topic and how this research fits within that broader topic?
6. Can you write a summary that focuses on the key findings and highlights the implications of the research to a mainstream audience.
7. Can you generate a glossary of any technical jargon or words that appear above a 12th-grade reading level.

When I try on [chatpdf.com](https://chatpdf.com), it's working well.
![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/125443259/1d33c28c-f714-4891-9a03-eb8db3945587)

Is anybody to solve this problem?
Thanks for your care.

**Comment by unholy-1** [comment]
which model are you using? gpt3.5 or 4?

**Comment by btmelody** [comment]
I use GPT3.5
Is that reason?

**Comment by montrealfiveonefour** [comment]
@ZackAllen1 thanks very much for pointing out LlamaIndex. Do you know how one could incorporate this feature into the chatbot given the current structure of the repository?
