### ISSUE TITLE
error [ErrorWithoutStackTrace: PineconeClient: Error calling upsert: ErrorWithoutStackTrace: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response]

### ISSUE THREAD

**Issue by OdinM13** [mayooear/gpt4-pdf-chatbot-langchain#298]
I searched the issues but no solution that was suggested worked. Dimensions are 1536 in pinecone and I even created a new us-east1-gcp environment as suggested. The keys are also correctly saved. The file is also not too big.

**Comment by baizhongying** [comment]
Solve the problem! mogul

**Comment by OdinM13** [comment]
> in .env in PINECONE_INDEX_NAME give only short name, for example only knowledgemining not entire adress
> 
> <img alt="image" width="176" src="https://user-images.githubusercontent.com/20611522/239343452-fb0a9826-805f-4fff-add3-a18788bc459a.png"> like this PINECONE_INDEX_NAME=knowledgemining

already tried that, did not work, but thanks for the Input

**Comment by OdinM13** [comment]
still not resolved
