### ISSUE TITLE
creating vector store... error 

### ISSUE THREAD

**Issue by HelloMorningStar** [mayooear/gpt4-pdf-chatbot-langchain#299]
metadata: {
      source: '/home/mio/gpt4-pdf-chatbot-langchain/docs/D8D21080-178E-4C0A-B112-6BC473330BF8-34667-000013F23C60340E.pdf',
      pdf_numpages: 336,
      loc: [Object]
    }
  },
  ... 231 more items
]
creating vector store...
error [ErrorWithoutStackTrace: PineconeClient: Error calling upsert: ErrorWithoutStackTrace: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response]
/home/mio/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:44
    throw new Error('Failed to ingest your data');
          ^

Error: Failed to ingest your data
    at run (/home/mio/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:44:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/home/mio/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:49:3)

Node.js v20.0.0

**Comment by cutedCha** [comment]
me too  .  u how to  ise vector store?
