### ISSUE TITLE
always waiting for response after one answer.

### ISSUE THREAD

**Issue by dadaoerv** [mayooear/gpt4-pdf-chatbot-langchain#30]
![image](https://user-images.githubusercontent.com/46274596/227119904-924e0dbc-25bf-4053-8c43-9001277c7332.png)

the bot won't answer twice.....

the showing question is for test, I change question for many times.

**Comment by dadaoerv** [comment]
can't deal with other documents

thanks for sharing

**Comment by mayooear** [comment]
Can you clarify the issue? This repo only handles PDF.
