### ISSUE TITLE
Unable to generate response:  Request failed with status code 401

### ISSUE THREAD

**Issue by shanshanRT** [mayooear/gpt4-pdf-chatbot-langchain#302]
Hi, thanks for making this project!

I have successfully ingested the data and started the app, but it was not able to generate a response with an error code 401:

Anyone has encountered the same issue? Is this referring to my pinecone or the chat-gpt authentication? Does this have anything to do with the pinecone environment? (currently using us-west1-gcp-free)  Please help! 

![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/133045484/fbfcbde1-07a8-4c86-8168-14191698b39e)

![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/133045484/b7e5cd97-1774-45c3-8640-cff8e66e8539)

Response Message:
![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/133045484/8f37111f-e8fa-4e44-87aa-ccb0e63c1686)

**Comment by mrrobot16** [comment]
I have this issue too :/ any word? @mayooear
