### ISSUE TITLE
Failed to initialize Pinecone Client

### ISSUE THREAD

**Issue by Gictor97** [mayooear/gpt4-pdf-chatbot-langchain#303]
when i ran ' npm run ingest  ', Pinecone client failed to initialize, even though its key and environment were correct

**Comment by wmgillett** [comment]
I had a similar issue when I ran this script the first few times and it would error out after logging "creating vector store..".  I tried smaller and smaller pdf files and nothing worked.  It was fixed for me when I moved from a free to a "pay as you go" openAI developer account.  This makes sense as I can see a dependency on openAI API in the ingest script via the OpenAIEmbeddings() process, which gets invoked right after the logging of the "creating vector store".

**Comment by sdvdskcv** [comment]
yes it is necessary to have access to the gpt 3.5 turbo API in order to run this application. This does mean you have to commit to the pay as you go subscription.
