### ISSUE TITLE
Save embeddings to save GPT Cost.

### ISSUE THREAD

**Issue by Kunstbanause** [mayooear/gpt4-pdf-chatbot-langchain#308]
# The Problem
Creating the embeddings with the GPT API costs a lot of money for large files! See 13 of May:
![grafik](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/3209654/c9e67621-a091-41de-8150-a1f192e29446)

These came in pairs for every page reload and re-upload of the pdf (even when its the same pdf):
![grafik](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/3209654/795929b1-5be3-4ad8-8e16-8afd6f0cf1d3)
For the 500 page pdf I was using this was a lot of tokens as you can see! More then the question itself.

# My Solution
I added way to **save** and **load** embeddings for the case where you would use the same pdf over and over again. See 14. of May!
This also loads a local pdf which you can specify in the first line: `pdfFileName = "<name>.pdf"` so you don't have to reupload again and again:

# Changes to app.py
Replace line 30: `# upload file`  to line 53:  `# show user input` with the following:
```
    pdfFileName = "<name>.pdf"
    dbFileName = "db_" + pdfFileName
    chunks = False

    embeddings = OpenAIEmbeddings()
 
    try: # Try to load embeddings first:
      knowledge_base = FAISS.load_local(dbFileName, embeddings)
      print("DB Found: loading...")
    except: # Generate if not found:

      if not chunks:
        print("Calculating Chunks")
        # extract the text
        pdf_reader = PdfReader(pdfFileName)
        text = ""
        for page in pdf_reader.pages:
          text += page.extract_text()
        
        # split into chunks
        text_splitter = CharacterTextSplitter(
          separator="\n",
          chunk_size=1000,
          chunk_overlap=200,
          length_function=len
        )
        chunks = text_splitter.split_text(text)
        print("Calculating Chunks... Success.")

        # create embeddings
        print("No DB found: Creating db...")
        knowledge_base = FAISS.from_texts(chunks, embeddings)
        knowledge_base.save_local(dbFileName)
```

**Comment by thienvip107** [comment]
good solution, and can you show me a solution for js code

**Comment by Aincvy** [comment]
Where is the app.py file ?

**Comment by Kunstbanause** [comment]
I think the author changed the project significantly and my solution no longer fits the current state current project, sorry.
