### ISSUE TITLE
Error: Failed to ingest your data

### ISSUE THREAD

**Issue by JonathanChen2023** [mayooear/gpt4-pdf-chatbot-langchain#309]
url: 'https://api.openai.com/v1/embeddings'
  },
  code: 'ERR_NETWORK',
  request: Request {
    [Symbol(realm)]: { settingsObject: [Object] },
    [Symbol(state)]: {
      method: 'POST',
      localURLsOnly: false,
      unsafeRequest: false,
      body: [Object],
      client: [Object],
      reservedClient: null,
      replacesClientId: '',
      window: 'client',
      keepalive: false,
      serviceWorkers: 'all',
      initiator: '',
      destination: '',
      priority: null,
      origin: 'client',
      policyContainer: 'client',
      referrer: 'client',
      referrerPolicy: '',
      mode: 'cors',
      useCORSPreflightFlag: false,
      credentials: 'same-origin',
      useCredentials: false,
      cache: 'default',
      redirect: 'follow',
      integrity: '',
      cryptoGraphicsNonceMetadata: '',
      parserMetadata: '',
      reloadNavigation: false,
      historyNavigation: false,
      userActivation: false,
      taintedOrigin: false,
      redirectCount: 0,
      responseTainting: 'basic',
      preventNoCacheCacheControlHeaderModification: false,
      done: false,
      timingAllowFailed: false,
      headersList: [HeadersList],
      urlList: [Array],
      url: URL {}
    },
    [Symbol(signal)]: AbortSignal { aborted: false },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON],
  attemptNumber: 7,
  retriesLeft: 0
}
f:\%E6%A1%8C%E9%9D%A2\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:44
    throw new Error('Failed to ingest your data');
          ^

Error: Failed to ingest your data
    at run (f:\%E6%A1%8C%E9%9D%A2\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:44:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (f:\%E6%A1%8C%E9%9D%A2\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:49:3)

Node.js v20.1.0

Anyone know how to fix this issure? I really need help, I tried couple ways, but it doesn't work out.
Here were the methonds I tried before:
1.change the pinecone Index name to short, like: dic
2.update the API Key

**Comment by JonathanChen2023** [comment]
Anyone know how to fix this issure? I really need help, I tried couple ways, but it doesn't work out.
Here were the methonds I tried before:
1.change the pinecone Index name to short, like: dic
2.update the API Key

**Comment by joemccann** [comment]
You need to change the `maxConcurrency` value in `ingest-data.ts`.

```js
const embeddings = new OpenAIEmbeddings({ maxConcurrency: 1 });
```

**Comment by cutedCha** [comment]
+1 my  i changed but not work 
![截屏2023-05-21 15 19 08](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/35335085/0e7dfc4c-36c6-4eaf-a4c1-b8ce54ca7eaa)
here  was a sudden springing to life of the teletype attached to that portion of Multivac. Five  words were printed: INSUFFICIENT DATA FOR MEANINGFUL ANSWER.   \\"No bet,\\" whispered Lupov. They left hurriedly.   By next morning, the two, plagued with throbbing head and cottony mouth, had forgotten  the incident.     Jerrodd, Jerrodine, and Jerrodette I and II watched the starry picture in the visiplate  change as the passage through hyperspace was completed in its non-time lapse. At once,  the even powdering of stars gave way to the predominance of a single bright shining disk,  the size of a marble, centered on the viewing-screen.   \\"That's X-23,\\" said Jerrodd confidently. His thin hands clamped tightly behind his back  and the knuckles whitened.   The little Jerrodettes, both girls, had experienced the hyperspace passage for the first time","and the knuckles whitened.   The little Jerrodettes, both girls, had experienced the hyperspace passage for the first time  in their lives and were self-conscious over the momentary sensation of insideoutness.  They burie`... 21336 more characters,
      url: 'https://api.openai.com/v1/embeddings'
    },
    request: Request {
      [Symbol(realm)]: [Object],
      [Symbol(state)]: [Object],
      [Symbol(signal)]: [AbortSignal],
      [Symbol(headers)]: [HeadersList]
    },
    data: { error: [Object] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON],
  attemptNumber: 7,
  retriesLeft: 0
}
/Users/smile/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:44
    throw new Error('Failed to ingest your data');
          ^


Error: Failed to ingest your data
    at run (/Users/smile/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:44:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/Users/smile/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:49:3)

**Comment by cutedCha** [comment]
![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/35335085/e34ad70a-bad5-4d81-b2e4-678ba43f585b)

**Comment by cutedCha** [comment]
i m

**Comment by cutedCha** [comment]
i‘m in china 。chatgpt un can use .use global proxy and a new key ,it worked。 fuck openai and china gfw～

**Comment by smallnine9** [comment]
@cutedCha 你那里能用了吗？求问怎么操作的

**Comment by JonathanChen2023** [comment]
> You need to change the `maxConcurrency` value in `ingest-data.ts`.
> 
> ```js
> const embeddings = new OpenAIEmbeddings({ maxConcurrency: 1 });
> ```

Thank you for your kindly reply, I tried it but it still doesn't work...
![111](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/133590183/24855dc7-4ba1-4682-bbc9-b658e8e56dfc)

**Comment by zenoncao** [comment]
@cutedCha I use global proxy,and it still times out...
