### ISSUE TITLE
translation issue with gpt-3.5-turbo

### ISSUE THREAD

**Issue by jonykpi** [mayooear/gpt4-pdf-chatbot-langchain#31]
I uploaded a pdf with english, and asked a Spanish question, its give me answer with english but i wanna get the answer with Spanish
https://prnt.sc/U3Sw2VhJPrqW

**Comment by ankri** [comment]
Translate these wrapping prompts to Spanish:
https://github.com/mayooear/gpt4-pdf-chatbot-langchain/blob/main/utils/makechain.ts#L7-L26

Or try adding a "answer in spanish" to the prompt. :)
