### ISSUE TITLE
Error: Failed to ingest your data

### ISSUE THREAD

**Issue by umerarif01** [mayooear/gpt4-pdf-chatbot-langchain#318]
Hi! I am getting this error. I have setup all of my env variables correctly. I don't know why it is not working.

```
PS C:\Users\UMER ARIF\Desktop\Projects\gpt4-pdf-chatbot-langchain> npm run ingest

> gpt4-langchain-pdf-chatbot@0.1.0 ingest    
> tsx -r dotenv/config scripts/ingest-data.ts

[WARN] Importing from 'langchain/document_loaders' is deprecated. Import from eg. 'langchain/document_loaders/fs/text' or 'langchain/document_loaders/web/cheerio' instead. See https://js.langchain.com/docs/getting-started/install#updating-from-0052 for upgrade instructions.
error TypeError: Object.hasOwn is not a function
    at null.DirectoryLoader (c:/Users/UMER%20ARIF/Desktop/Projects/gpt4-pdf-chatbot-langchain/node_modules/langchain/dist/document_loaders/fs/directory.js:41:24)
    at null.run (c:\Users\UMER ARIF\Desktop\Projects\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:15:29)
    at null.<anonymous> (c:\Users\UMER ARIF\Desktop\Projects\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:49:9)
    at null.<anonymous> (c:\Users\UMER ARIF\Desktop\Projects\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:51:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
c:\Users\UMER ARIF\Desktop\Projects\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:44
    throw new Error('Failed to ingest your data');
          ^

Error: Failed to ingest your data
    at null.run (c:\Users\UMER ARIF\Desktop\Projects\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:44:11)
    at null.<anonymous> (c:\Users\UMER ARIF\Desktop\Projects\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:49:9)
    at null.<anonymous> (c:\Users\UMER ARIF\Desktop\Projects\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:51:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by khalidfarooq** [comment]
facing the same issue

**Comment by umerarif01** [comment]
> facing the same issue

Let me know bro if you find a solution.

**Comment by nexty5870** [comment]
Make sure you have your .env setup right - 

PINECONE_INDEX_NAME is the name of your index ( I got it confuse at first and run into the same issue as you had) changed it and it worked

**Comment by EgyptianBrince** [comment]
facing same issue

**Comment by wail-asad** [comment]
@umerarif01 @khalidfarooq @EgyptianBrince 
Make sure from Pinecone at create index, the Max Dimensions must be 1536.

**Comment by khalidfarooq** [comment]
The configuration is correct index name , dimensions, environment
Still it's not working

**Comment by umerarif01** [comment]
> @umerarif01 @khalidfarooq @EgyptianBrince 
> Make sure from Pinecone at create index, the Max Dimensions must be 1536.

Despite setting the dimensions to 1536, the script was still giving error. However, I was able to resolve the issue by utilizing the following Python script to ingest the document. As a result, the chatbot is now functioning smoothly.

You can access the Python script at the following link: https://github.com/ucl98/pinecone_ingest_python_implementation

Make sure to follow all of the instructions properly if you are going to use it.

**Comment by EgyptianBrince** [comment]
its just a formatting error because langchain had a new update, replace line 13 with this 

export const run = async () => {
  try {
    /*load raw docs from the all files in the directory */
    const directoryLoader = new DirectoryLoader(filePath, {
      '.pdf': (path) => new CustomPDFLoader(path, '/pdf'),
    });

Itll work fine afterwards (remember to save file)

Essentially all your doing is adding the ", '/pdf'" in the new DirectoryLoader

**Comment by EgyptianBrince** [comment]
> @umerarif01 @khalidfarooq @EgyptianBrince Make sure from Pinecone at create index, the Max Dimensions must be 1536.

its just a formatting error because langchain had a new update, replace line 13 with this 

export const run = async () => {
  try {
    /*load raw docs from the all files in the directory */
    const directoryLoader = new DirectoryLoader(filePath, {
      '.pdf': (path) => new CustomPDFLoader(path, '/pdf'),
    });

Itll work fine afterwards (remember to save file)

Essentially all your doing is adding the ", '/pdf'" in the new DirectoryLoader

**Comment by EgyptianBrince** [comment]
> facing the same issue

its just a formatting error because langchain had a new update, replace line 13 with this 

export const run = async () => {
  try {
    /*load raw docs from the all files in the directory */
    const directoryLoader = new DirectoryLoader(filePath, {
      '.pdf': (path) => new CustomPDFLoader(path, '/pdf'),
    });

Itll work fine afterwards (remember to save file)

Essentially all your doing is adding the ", '/pdf'" in the new DirectoryLoader
