### ISSUE TITLE
directoryLoader.load() not working?

### ISSUE THREAD

**Issue by sean-s14** [mayooear/gpt4-pdf-chatbot-langchain#320]
The line below in `scripts/ingest-data.ts` is returning an empty array.
```ts
const docs = await textSplitter.splitDocuments(rawDocs);
```

I logged `rawDocs` and it displayed the `source` and `pdf_numpages` metadata correctly however the `pageContent` is just a bunch of new line strings concatenated together like so `'\n' + '\n' + '\n' ...`

Running `npm run ingest` returns the following:
```bash
[WARN] Importing from 'langchain/document_loaders' is deprecated. Import from eg. 'langchain/document_loaders/fs/text' 
or 'langchain/document_loaders/web/cheerio' instead.
See https://js.langchain.com/docs/getting-started/install#updating-from-0052 for upgrade instructions.
(node:4904) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
split docs []
creating vector store...
ingestion complete
```

**Edit**
Turns out this is a problem I'm having with just one text book. Unsure what to do.

**Comment by bookofbash** [comment]
Here's what I did with the same error. Also had to use a different pdf, but it worked. 

Link to comment

https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/318#issuecomment-1557525044

**Comment by EgyptianBrince** [comment]
its just a formatting error because langchain had a new update, replace line 13 with this 

export const run = async () => {
  try {
    /*load raw docs from the all files in the directory */
    const directoryLoader = new DirectoryLoader(filePath, {
      '.pdf': (path) => new CustomPDFLoader(path, '/pdf'),
    });

Itll work fine afterwards (remember to save file)

**Comment by twut** [comment]
Got the same issue here.
docs is empty.
`[WARN] Importing from 'langchain/document_loaders' is deprecated. Import from eg. 'langchain/document_loaders/fs/text' or 'langchain/document_loaders/web/cheerio' instead. See https://js.langchain.com/docs/getting-started/install#updating-from-0052 for upgrade instructions.
split docs []`

Have tried to add the 2nd argument, '/pdf', but still not working. My langchain version is 0.0.82.
