### ISSUE TITLE
npm run ingest error

### ISSUE THREAD

**Issue by MrArabAi** [mayooear/gpt4-pdf-chatbot-langchain#325]
Hello, there
i was wonderding why do i get this error ? i did everyhing right and set up new index on pincone. Can you help please?

btw: i have pdf file inside docs file 

PS D:\Chatbot AI\gpt4-pdf-chatbot-langchain> npm run ingest

> gpt4-langchain-pdf-chatbot@0.1.0 ingest
> tsx -r dotenv/config scripts/ingest-data.ts

error [Error: ENOTDIR: not a directory, scandir 'D:\Chatbot AI\gpt4-pdf-chatbot-langchain\docs\tesla.pdf'] {
  errno: -4052,
  code: 'ENOTDIR',
  syscall: 'scandir',
  path: 'D:\\Chatbot AI\\gpt4-pdf-chatbot-langchain\\docs\\tesla.pdf'
}
d:\Chatbot AI\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:46
    throw new Error('Failed to ingest your data');
          ^

Error: Failed to ingest your data
    at run (d:\Chatbot AI\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:46:11)
    at <anonymous> (d:\Chatbot AI\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:51:3)

Node.js v18.16.0

**Comment by boyuan99** [comment]
I think it may be that your file path is wrong. The file path should be the folder where the pdf file is stored instead of the file itself. Hope this helps
