### ISSUE TITLE
Running error：ETIMEDOUT 

### ISSUE THREAD

**Issue by YongjiangXu** [mayooear/gpt4-pdf-chatbot-langchain#335]
**I have something error, but i can't solve this, hope someone could help me:**
error Error: connect ETIMEDOUT 108.160.163.117:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '108.160.163.117',
  port: 443,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.2.1',
      Authorization: 'Bearer sk-xxx',
      'Content-Length': 56
    },
    method: 'post',
    data: '{"model":"text-embedding-ada-002","input":"who are you"}',
    url: 'https://api.openai.com/v1/embeddings'
  },

**Comment by JiqiY** [comment]
got the same issue, checked everything not sure what went run. It seems like connection to OpenAI API is not successful

**Comment by YongjiangXu** [comment]
I succeeded later. I changed the agent to TUN mode. You can try it, I hope it will help you.

**Comment by damonLi22** [comment]
> I succeeded later. I changed the agent to TUN mode. You can try it, I hope it will help you.

I used vpn of clash,  I enable the tun mode with clash gui.  But the issue don't sovled.   so how do you setup with tun mode?

**Comment by damonLi22** [comment]
> > I succeeded later. I changed the agent to TUN mode. You can try it, I hope it will help you.
> 
> I used vpn of clash, I enable the tun mode with clash gui. But the issue don't sovled. so how do you setup with tun mode?

I succeeded .    I changed the mode to tun mode  with clash for windows.
