### ISSUE TITLE
how to switch my reply to Chinese

### ISSUE THREAD

**Issue by choogoo** [mayooear/gpt4-pdf-chatbot-langchain#336]
This is an exciting project. My native language is Chinese. Does anyone know how to switch my reply to Chinese

**Comment by YongjiangXu** [comment]
你好，我想可以修改一下提示模板，使机器用中文输出。另外我想向您请教下如何运行这个项目，我已经成果提取pdf到pinecone上，但每次开始运行就会出现服务器连接超时的错误，据说是需要额外设置代理，请问您可以指点一下吗

**Comment by choogoo** [comment]
> 你好，我想可以修改一下提示模板，使机器用中文输出。另外我想向您请教下如何运行这个项目，我已经成果提取pdf到pinecone上，但每次开始运行就会出现服务器连接超时的错误，据说是需要额外设置代理，请问您可以指点一下吗：#335

是的，你需要使用代理来保证当前环境可用通过api访问openai及pinecone的代理服务，设置终端代理的命令格式

```
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
```

**Comment by j796160836** [comment]
Related to #329 #340

**Comment by KonngExplorer** [comment]
我通过以下方式解决了

修改ingest-data.ts如下：

```
import {HttpsProxyAgent} from "https-proxy-agent";
const agent = new HttpsProxyAgent('http://127.0.0.1:33210')
      const embeddings = new OpenAIEmbeddings({
          verbose: true,
          openAIApiKey: '{your key}'
      }, {
          baseOptions: {
              proxy: false,
              httpAgent: agent,
              httpsAgent: agent,
          },
      });
```
注意，你需要安装https-proxy-agent
