### ISSUE TITLE
Deleting a namespace

### ISSUE THREAD

**Issue by sahinutar** [mayooear/gpt4-pdf-chatbot-langchain#337]
Hi,

Working with the examples provided and ingesting the same doc over and over again, realized the same chunks are added as new vectors to the namespace increasing the total vectors in the namespace with each iteration. Not sure how I get ids once vectors are created using from_documents method. 

Any way to get vector ids of some namespace created with langchain's from_documents method and iterate over and delete one by one? Or perhaps better a way to remove a namespace completely without having to know the vector ids?

Thanks a lot

Ş.

**Comment by ashokrs** [comment]
![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/35771744/bd710607-aab5-4881-938d-b0e93270b28c)
