### ISSUE TITLE
npm run ingest / Pinecone error 

### ISSUE THREAD

**Issue by nicolasmaldonadoj** [mayooear/gpt4-pdf-chatbot-langchain#350]
Hi, Im having problems with Pinecone. I dont know what the error might be. 

creating vector store...
error [PineconeError: PineconeClient: Error calling upsert: PineconeError: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response]
/Users/nicolasmaldonado/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:46
    throw new Error('Failed to ingest your data');
          ^

Error: Failed to ingest your data
    at run (/Users/nicolasmaldonado/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:46:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/Users/nicolasmaldonado/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:51:3)

**Comment by Heymusky** [comment]
Make sure to use the proper name of your index. For example mine is just named index.
![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/59809751/7cf0b343-e65b-42c6-bc81-8968b2f6c3f2)
Also set your dimensions to 1536

**Comment by oberoir080** [comment]
I managed to fix the issue by changing my open ai api key, earlier I was using a free trial account and now I am using a paid one, and it works flawlessly.

**Comment by shemtovsamuel** [comment]
Hello, I have exactly the same error, while I followed everything well I put the name index with a size of 1536 for Pinecone and I regenerate a key api pay chat gpt but it still does not work ... Can you help me?

**Comment by niccolley-alation** [comment]
I rotated my pinecone API key, waited 10 min as it updated, and then boom inserts galore.
