### ISSUE TITLE
how can I add logs / store the current logs?

### ISSUE THREAD

**Issue by sebastianneacsu** [mayooear/gpt4-pdf-chatbot-langchain#362]
I deployed in an amazon ec2 instance but after a while the application dies. how can I store the logs that appear in console? I tried several options (like winston, etc) but without success. 
Thanks!

**Comment by groovybits** [comment]
I had one here: https://github.com/groovybits/gaib/commit/52b9599bb81b65a6aea07d854b77808a9df0fb4a#diff-349e858709586b934dbba2f345b55125c0f2f3eabd3430388c1c3a7cbf40e6b9 I added. Worked okay, logged into .next/ though :( so needs some crafting, and doesn't work with Vercels etc of course.

Streaming output to somewhere is ideal, in Cloudrun it logs the console.log output that is backend. This logged client end too :D.
