### ISSUE TITLE
Strange PDF Source Output

### ISSUE THREAD

**Issue by ogiel** [mayooear/gpt4-pdf-chatbot-langchain#363]
Hey all, I am not quite sure whether this is an actual issue to be honest but I would like to shed some light to this behavior. 

After indexing the DSA (Digital Services Act), I can ask questions and get overall decent answers; However, the text in the sources look like this:

`reach the dimension of a ver y larg e online platf or m or a ver y large online searc h engine, with the related imp act on the inte rnal mark et.`

The text is rather broken, making it harder to read than necessary. Is this because the PDF file has issues, the PDF reader has issues, it shows me converted vectors meaning that the underlying text is correct or something completely different? 

I tried to manually copy and past a piece of text from the PDF to see if the text is broken there also but when I paste it the text still looks fine.

Is this expected behavior? And if not; does anyone know how to fix / improve?

**Comment by valoricDe** [comment]
PDF is a crapy but flexible format which basically just places bits of text to certain absolute positions. So as a PDF reader is is hard to find out if a bit of text "reach the dimension of a ver" belongs to the next block "y". I guess the langchain reader is not as sophisticated as real PDF reader apps and thus just creates whitespaces between blocks of text

**Comment by valoricDe** [comment]
I had the same problem back then with https://github.com/mozilla/pdf.js/ and you would basically need to create heuristics to know when to place something together and when not
