### ISSUE TITLE
How to make it generate more output? 

### ISSUE THREAD

**Issue by ihop-56** [mayooear/gpt4-pdf-chatbot-langchain#364]

**Comment by groovybits** [comment]
More documents than the default 4 can generate more. I think more history can do it, and possibly setting max_tokens but not necessarily. Technically max_tokens should do it yet I don't see that always, it depends again on if you asked for something big enough. Possibly upping the temperature? not sure.

From what I can tell it is mainly the more documents or else the question + document data returned and how much it could build from it + history somewhat.
