### ISSUE TITLE
Does it support a variety of multilingual documents and PDFs?

### ISSUE THREAD

**Issue by YIN-Renlong** [mayooear/gpt4-pdf-chatbot-langchain#369]
First of all, I want to express my gratitude for this project. 

Are there any special processes or document processing improvements that need to be implemented for the mixed use of multilingual documents or PDFs? Or does it intend to pose a query in a certain language? 

Cite this additional YouTube comment:

```
It works SO GOOOD with english pdfs, but when i try non-english it struggles a lot, any idea why?

OpenAI's embedding function isn't optimized for multilingual. You can try Cohere's embedding api instead.

```

Exists a method of integration?

Thanks.

**Comment by anjopater** [comment]
@YIN-Renlong I did some tests using a document in another language PT-BR and it worked well for me.
