### ISSUE TITLE
Failed to connect to localhost:3000

### ISSUE THREAD

**Issue by taozangyearone** [mayooear/gpt4-pdf-chatbot-langchain#374]
I tried to open the localhost3000 after running npm run dev, and it failed to make connection. Thanks for any help!
![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/123785167/e112edeb-8016-4485-933b-6cf93c199751)

![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/123785167/ce3f6f6e-b492-4277-bf29-bc88a0584479)

**Comment by shafran666** [comment]
I have the same error but it worked for me one time, when i re-ingested the new pdf and disconnected the running it anew didn't work the same as for @taozangyearone
