### ISSUE TITLE
Chat history is not included in the prompt (model is not aware of previous interactions)

### ISSUE THREAD

**Issue by Dlas1212** [mayooear/gpt4-pdf-chatbot-langchain#393]
The issue persists with this. Ticket should be re opened. When using `ConversationalRetrievalQAChain` the history if your message does not persist. 

Detail: I am using [Externally Managed Memory](https://js.langchain.com/docs/modules/chains/popular/chat_vector_db#externally-managed-memory), which clearly states `you can also pass the chat history in explicitly by omitting the memory option and supplying a chat_history string or array of HumanMessages and AIMessages directly into the chain.call method`

When you pass in your history and ask it something along of lines of "My name is Joe", then AI will usually respond with "Hi Joe, how are you?" and if your follow up question is "What is my name?" Even when passing in the `chat_history` the AI will respond with `I do not have access to that information`. 

The closed ticket that should be re-opened because this is not solved: [https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/65](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/65)

**Comment by harrycruz** [comment]
Hello, I am currently facing the exact same issue. It looks `chat_history` is being completely ignore. When printing the chain's reponse, the only items in the chat_history are the question and answer itself. See it below:

`{'question': 'Options for financing', 'chat_history': [HumanMessage(content='Options for financing', additional_kwargs={}, example=False), AIMessage(content='There is no information provided in the given context about options for car financing.', additional_kwargs={}, example=False)], 'answer': 'There is no information provided in the given context about options for car financing.'}`

**Comment by jklein33** [comment]
Anyone come up with a solution to this?

**Comment by AravinthSankar-hash** [comment]
Tried, still no solution.
Is the issue only with langchainJs or in python also ?

**Comment by saud121** [comment]
anyone have a solution?

**Comment by Dlas1212** [comment]
@saud121 @jklein33 @harrycruz 

I believe this is still active right?

**Comment by jklein33** [comment]
@Dlas1212 yeah the solution is to not use langchain bc it's trash. My system improved dramatically by removing langchain.
