### ISSUE TITLE
The requested feature 'Namespaces' is not  supported by the current index type 'Starter'.] 

### ISSUE THREAD

**Issue by mallet-zn** [mayooear/gpt4-pdf-chatbot-langchain#406]
error [PineconeError: PineconeClient: Error calling upsert: PineconeError: The requested feature 'Namespaces' is not 
supported by the current index type 'Starter'.] 

I try to after settinging up my env and always show me this error

**Comment by minhthongdoan** [comment]
I remove the namespace in pinecone.ts and it resolved
`const PINECONE_NAME_SPACE = ''`

**Comment by erok415** [comment]
To resolve this error completely for Pinecone starter accounts. 

1. Go to config/pinecone.ts and comment out `const PINECONE_NAME_SPACE = ''`
2. In the same file change 
```typescript
export { PINECONE_INDEX_NAME, PINECONE_NAME_SPACE };
```
to 
```typescript
export { PINECONE_INDEX_NAME };
```
3. Go to `scripts/ingest-data.ts` and change 
```typescript
import { PINECONE_INDEX_NAME, PINECONE_NAME_SPACE } from '@/config/pinecone';
```
to
```typescript
import { PINECONE_INDEX_NAME } from '@/config/pinecone';
```
4. In the same file, go to line 41 and comment out 
```typescript
namespace: PINECONE_NAME_SPACE,
```
5. Go to `pages/api/chat.ts` and repeat steps 3 and 4 above. For Step 4, look to line 39 and comment out 
```typescript
namespace: PINECONE_NAME_SPACE, //namespace comes from your config folder
```
