### ISSUE TITLE
PineconeClient is deprecated

### ISSUE THREAD

**Issue by Victor-Timi** [mayooear/gpt4-pdf-chatbot-langchain#408]
I just wrote my import statement which is:

import { PineconeClient } from "@pinecone-database/pinecone";      

But here is what i am getting:

'PineconeClient' is deprecated.ts(6385)
index.d.ts(10, 4): The declaration was marked as deprecated here.

**Comment by nisuJaiswal** [comment]
Go to package.json and compare the versions of pinecone-database, install the same version as this repo.
