### ISSUE TITLE
Support for BIG PDFs?(like 500pages)

### ISSUE THREAD

**Issue by xnpeter** [mayooear/gpt4-pdf-chatbot-langchain#409]
Thank you for creating this project; it's been very useful. I have a few minor questions:

- When working with very long PDFs, for example, ones that are 500 pages, or when dealing with multiple documents, the API requests seem to become unresponsive. Would it be possible to add a feature for chunked uploading?
- Currently, if I add a new document to the 'doc' folder, do I need to re-ingest all the files again? Is it possible to implement an incremental ingest feature?

**Comment by YIN-Renlong** [comment]
My experience is relevant to the first question, and I even have several books that are over 500 pages long. However, you must be mindful of the pinecone.io free tier's pod capacity, which may be exceeded - premium projects are certainly doable. If you are not prepared to pay and the book has a huge capacity, I would advise to check out this branch https://github.com/mayooear/gpt4-pdf-chatbot-langchain/tree/feat/chroma to deploy the vector database (ChromaDB) locally.

I'm also seeking an answer to the following second question: https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/415

Cheers,
