### ISSUE TITLE
Alternative for OpenAI for embeddings?

### ISSUE THREAD

**Issue by nisuJaiswal** [mayooear/gpt4-pdf-chatbot-langchain#414]
Is there any another alternative way for embed pdf using model instead of OpenAI?
Because openai will cost more with increase in pdf size. So, if there any other model of langchain is there that embeds pdfs, then please suggest!

**Comment by govind-kumarr** [comment]
@nisuJaiswal  Hugging face is only option left i guess.

**Comment by araza110** [comment]
> @nisuJaiswal Hugging face is only option left i guess.

Can you show in code, how do you implement hugging face instead of openAI Embedding?
