### ISSUE TITLE
Conversion of code into Python

### ISSUE THREAD

**Issue by MuhammadIshaq-AI** [mayooear/gpt4-pdf-chatbot-langchain#439]
Hi sir, I have been using your code for many months, some issue I face is that i don't understand some modules and typescripts for the node.js, level of understanding for nodejs for me has become quite difficult, is there a way to convert the current repo into python?

**Comment by VigneshDevelops** [comment]
Please check this out for Python  
https://github.com/VigneshDevelops/chat-with-docs
