### ISSUE TITLE
Explain data ingestion code.

### ISSUE THREAD

**Issue by araza110** [mayooear/gpt4-pdf-chatbot-langchain#451]
I'm seeking assistance in understanding a code implementation within my NestJS application. The API is designed to convert PDF documents into vectors and subsequently store them within a Pinecone database. However, upon data ingestion, I'm encountering a discrepancy in the number of vectors stored compared to the expected output from the original code.

To illustrate, executing "yarn ingest" within the original code yields 972 vectors. Yet, when attempting the same process with my code, utilizing an identical file, the resulting number of vectors is 950. Why is that so?! What am I doing wrong?

Please advise on potential factors contributing to this discrepancy and any corrective measures I can implement to achieve consistency.

My NEST JS Code:
```
import { OpenAIEmbeddings } from 'langchain/embeddings/openai';
import { RecursiveCharacterTextSplitter } from 'langchain/text_splitter';
import { PineconeStore } from 'langchain/vectorstores/pinecone';

 
 /**
   * @description This API is linked with s3 File upload API. This API is used to create vector store from the uploaded PDF file.
   * @param {string} url : S3 URL of the uploaded PDF file
   * @param {string} namespace : Name of the vector store namespace (unique)
   */
  async create(url: string, namespace: string): Promise<void> {
    if (!url) throw new BadRequestException('URL is required');
    if (!namespace) throw new BadRequestException('Vector Name is required');

    try {
      const rawDocs = await this.loadPDF(url as string);

      const textSplitter = new RecursiveCharacterTextSplitter({
        chunkSize: 1000,
        chunkOverlap: 200,
      });

      const docs = await textSplitter.splitDocuments(rawDocs);

      console.log('Creating vector store...');

      /*create and store the embeddings in the vectorStore*/
      const embeddings = new OpenAIEmbeddings({
        openAIApiKey: process.env.OPEN_AI_SK as string,
      });

      const index = this.pinecone.Index(
        process.env.PINECONE_INDEX_NAME as string,
      ); 

      await PineconeStore.fromDocuments(docs, embeddings, {
        pineconeIndex: index,
        namespace,
        textKey: 'text',
      });
    } catch (err) {
      const errorMessage =
        err.response?.data?.error?.message ?? "Couldn't create vector store";

      Logger.error(errorMessage, err.stack, 'LangchainService');

      throw new HttpException(
        {
          status: HttpStatusCode.InternalServerError,
          error: errorMessage,
        },
        HttpStatusCode.InternalServerError,
      );
    }
  }
```

**Comment by araza110** [comment]
Please explain this code block 

```
  const textSplitter = new RecursiveCharacterTextSplitter({
        chunkSize: 1000,
        chunkOverlap: 200,
      });
```

Also what is textKey? 

```
 await PineconeStore.fromDocuments(docs, embeddings, {
        pineconeIndex: index,
        namespace,
        textKey: 'text',
      });
```

**Comment by araza110** [comment]
Hi,@dosbut Please explain this code block 

```
  const textSplitter = new RecursiveCharacterTextSplitter({
        chunkSize: 1000,
        chunkOverlap: 200,
      });
```

Also what is textKey? 

```
 await PineconeStore.fromDocuments(docs, embeddings, {
        pineconeIndex: index,
        namespace,
        textKey: 'text',
      });
```

**Comment by jkobb510** [comment]
`textSplitter` splits PDF documents into smaller parts called "chunks".
    chunkSize - each chunk should have a maximum of 1000 characters. 
    chunkOverlap - how much overlap there should be between adjacent chunks (200 characters)

say we load a document containing: 

> "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae mauris nec nisl imperdiet placerat. Nullam in semper velit. Phasellus congue varius felis, in efficitur tellus tempor sit amet. Duis mollis tincidunt ex, ac feugiat metus consectetur ut. Sed tincidunt lacus sed felis fringilla, eu blandit massa ullamcorper. Aliquam pulvinar, nisl eu consectetur dignissim, mi erat fermentum sapien, eu ultrices turpis lectus a nunc."


```
const rawDocs = await directoryLoader.load();

const textSplitter = new RecursiveCharacterTextSplitter({
  chunkSize: 1000,
  chunkOverlap: 200,
});

const docs = await textSplitter.splitDocuments(rawDocs);
console.log('split docs', docs);
```
We get:
```
[
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae mauris nec nisl imperdiet placerat. Nullam in semper velit. Phasellus congue varius felis, in efficitur tellus tempor sit amet. Duis mollis tincidunt ex, ",
  "ac feugiat metus consectetur ut. Sed tincidunt lacus sed felis fringilla, eu blandit massa ullamcorper. Aliquam pulvinar, nisl eu consectetur dignissim, mi erat fermentum sapien, eu ultrices turpis lectus a nunc."
]
```

```
await PineconeStore.fromDocuments(docs, embeddings, {
  pineconeIndex: index,
  namespace,
  textKey: 'text',
});
```

`textKey` tells the code which part of each document should be used for generating embeddings. In this case, it expects each element in the docs array to have a property called 'text'. Each document object has a text property containing the text to be used for generating embeddings.

e.g.
`{ 
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae mauris nec nisl imperdiet placerat. Nullam in semper velit. Phasellus congue varius felis, in efficitur tellus tempor sit amet. Duis mollis tincidunt ex, ", 
    text:  "ac feugiat metus consectetur ut. Sed tincidunt lacus sed felis fringilla, eu blandit massa ullamcorper. Aliquam pulvinar, nisl eu consectetur dignissim, mi erat fermentum sapien, eu ultrices turpis lectus a nunc."
  };`
