### ISSUE TITLE
Add support for Pinecone Serverless

### ISSUE THREAD

**Issue by JPaulMora** [mayooear/gpt4-pdf-chatbot-langchain#457]
Hello, I think it would be a great addition to have this new Pinecone feature added here. Serverless blog post for reference: https://www.pinecone.io/blog/serverless/

**Comment by edmundman** [comment]
bump

**Comment by precupstefan** [comment]
@JPaulMora @edmundman 

you have to bump pinecone-database to latest `npm install @pinecone-database/pinecone@latest`

then change in   [pinecone-client.ts](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/blob/main/utils/pinecone-client.ts)

```import { Pinecone } from '@pinecone-database/pinecone';

const pc = new Pinecone({
    apiKey: "YOUR_API_KEY",
    environment: "YOUR_ENVIRONMENT",
});
```

to 

```import { Pinecone } from '@pinecone-database/pinecone';

const pc = new Pinecone({
    apiKey: 'YOUR_API_KEY' 
});
```

**Comment by JPaulMora** [comment]
Thanks @precupstefan Will try this later

**Comment by CarmichaelAJ** [comment]
This did not work for me, I can't initialize pinecone now..

**Comment by Ravel36** [comment]
Has anyone been able to get this to work? I tried what was mentioned above, but my the changes recommended doesn't match what is actually in the pinecone-client.ts file.

**Comment by sulphh** [comment]
Bump

**Comment by CarmichaelAJ** [comment]
Would you mind pasting your pinecone-client.ts?

Im also confused to why Chat.ts has `import {PineconeStore} from "@langchain/pinecone"`
