### ISSUE TITLE
[Error: Failed to ingest your data]

### ISSUE THREAD

**Issue by zyx33331** [mayooear/gpt4-pdf-chatbot-langchain#46]
creating vector store...
error [Error: PineconeClient: Project name not set. Call init() first.]
g:\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:51
    throw new Error('Failed to ingest your data');
          ^

[Error: Failed to ingest your data]

**Comment by hrushik98** [comment]
check if the file path is correct or not.

**Comment by hugodotlau** [comment]
I have a similar question

error [Error: PineconeClient: Error calling upsert: Error: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response]
/Users/liuchenghui01/Development/JavaScript/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:51
    throw new Error('Failed to ingest your data');
          ^

**Comment by glide-the** [comment]
I also encountered this problem, which occurred randomly,

**Comment by zyx33331** [comment]
The file path is correct.
&nbsp; &nbsp; metadata: { source: 'MorseVsFrederick.pdf' }
&nbsp; },
&nbsp; Document {
&nbsp; &nbsp; pageContent: 'its educational mission to include solidarity with our soldiers \n' +
&nbsp; &nbsp; &nbsp; 'and&nbsp; their&nbsp; families&nbsp; and&nbsp; thus&nbsp; could&nbsp; have&nbsp; attempted&nbsp; to&nbsp; outlaw \n' +
&nbsp; &nbsp; &nbsp; 'the&nbsp; wearing&nbsp; of&nbsp; black&nbsp; armbands&nbsp; on&nbsp; the&nbsp; ground&nbsp; that&nbsp; they&nbsp; un­\n' +
&nbsp; &nbsp; &nbsp; 'dermined&nbsp; this&nbsp; mission.&nbsp; &nbsp; Alternatively,&nbsp; a&nbsp; school&nbsp; could&nbsp; have \n' +
&nbsp; &nbsp; &nbsp; 'defined&nbsp; its&nbsp; educational&nbsp; mission&nbsp; to&nbsp; include&nbsp; the&nbsp; promotion&nbsp; of \n' +
&nbsp; &nbsp; &nbsp; 'world&nbsp; peace&nbsp; and&nbsp; could&nbsp; have&nbsp; sought&nbsp; to&nbsp; ban&nbsp; the&nbsp; wearing&nbsp; of \n' +
&nbsp; &nbsp; &nbsp; 'buttons&nbsp; expressing&nbsp; support&nbsp; for&nbsp; the&nbsp; troops&nbsp; on&nbsp; the&nbsp; ground \n' +
&nbsp; &nbsp; &nbsp; 'that the buttons signified approval of war.&nbsp; &nbsp; The “educational \n' +
&nbsp; &nbsp; &nbsp; 'mission”&nbsp; argument&nbsp; would&nbsp; give&nbsp; public&nbsp; school&nbsp; authorities&nbsp; a \n' +
&nbsp; &nbsp; &nbsp; 'license&nbsp; &nbsp;to&nbsp; &nbsp;suppress&nbsp; &nbsp;speech&nbsp; &nbsp;on&nbsp; &nbsp;political&nbsp; &nbsp;and&nbsp; &nbsp;social&nbsp; &nbsp;issues \n' +
&nbsp; &nbsp; &nbsp; 'based&nbsp; on&nbsp; disagreement&nbsp; with&nbsp; the&nbsp; viewpoint&nbsp; expressed.&nbsp; &nbsp; The \n' +
&nbsp; &nbsp; &nbsp; 'argument,&nbsp; therefore,&nbsp; strikes&nbsp; at&nbsp; the&nbsp; very&nbsp; heart&nbsp; of&nbsp; the&nbsp; First \n' +
&nbsp; &nbsp; &nbsp; 'Amendment.',
&nbsp; &nbsp; metadata: { source: 'MorseVsFrederick.pdf' }
&nbsp; },
&nbsp; ... 78 more items
]
creating vector store...
error [Error: PineconeClient: Project name not set. Call init() first.]
g:\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:51
&nbsp; &nbsp; throw new Error('Failed to ingest your data');
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^




[Error: Failed to ingest your data]





云飞扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mayooear/gpt4-pdf-chatbot-langchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月24日(星期五) 晚上9:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mayooear/gpt4-pdf-chatbot-langchain] [Error: Failed to ingest your data] (Issue #46)





 
check if the file path is correct or not.

**Comment by Aditya1404Sal** [comment]
> I have a similar question， already checked file path, Pineone config: index name, dimensions value
> 
> error [Error: PineconeClient: Error calling upsert: Error: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response] /Users/liuchenghui01/Development/JavaScript/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:51 throw new Error('Failed to ingest your data'); ^

is your file size above 2 mb ?

**Comment by petko5** [comment]
I didn't have access to gpt-4 so I resolved this error by reducing pdf pages ingested, chunk size and overlap.

**Comment by zyx33331** [comment]
> I didn't have access to gpt-4 so I resolved this error by reducing pdf pages ingested, chunk size and overlap.

Thank you for your answer, that's probably the reason.

**Comment by leoliuzcl** [comment]
> I didn't have access to gpt-4 so I resolved this error by reducing pdf pages ingested, chunk size and overlap.

how do you set chunk size and overlap?

**Comment by naticio** [comment]
> > I have a similar question， already checked file path, Pineone config: index name, dimensions value
> > error [Error: PineconeClient: Error calling upsert: Error: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response] /Users/liuchenghui01/Development/JavaScript/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:51 throw new Error('Failed to ingest your data'); ^
> 
> is your file size above 2 mb ?

mine is, why? should be less than 2 mb?
