### ISSUE TITLE
error [TypeError: this.embeddings.embedQuery is not a function]

### ISSUE THREAD

**Issue by edwinx3344** [mayooear/gpt4-pdf-chatbot-langchain#58]
error [TypeError: this.embeddings.embedQuery is not a function]
I've already had vectors stored in pinecone, and after submitting a question, there is an error.

**Comment by mayooear** [comment]
This is the cause of your error:

```
  const vectorStore = await PineconeStore.fromExistingIndex(
    index,
    new OpenAIEmbeddings({}),
    'text',
    PINECONE_NAME_SPACE, //optional
  );
```

Cross check that your using the version of LangChain as per the repo and set the NAME_SPACE to match the one on Pinecone.
