### ISSUE TITLE
Error: Failed to ingest your data

### ISSUE THREAD

**Issue by yaya6630170** [mayooear/gpt4-pdf-chatbot-langchain#60]
I extracted parts of the code except for the pdf content. Please I just can't find the bug.....

**Comment by yaya6630170** [comment]
error [Error: Network Error] {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [AsyncFunction: fetchAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.2.1',
      Authorization: 'Bearer sk-XXXXX'(here is the openai api key)
    },
    method: 'post', 




url: 'https://api.openai.com/v1/embeddings'
  },
  code: 'ERR_NETWORK',
  request: Request {
    [Symbol(realm)]: { settingsObject: [Object] },
    [Symbol(state)]: {
      method: 'POST',
      localURLsOnly: false,
      unsafeRequest: false,
      body: [Object],
      client: [Object],
      reservedClient: null,
      replacesClientId: '',
      window: 'client',
      keepalive: false,
      serviceWorkers: 'all',
      initiator: '',
      destination: '',
      priority: null,
      origin: 'client',
      policyContainer: 'client',
      referrer: 'client',
      referrerPolicy: '',
      mode: 'cors',
      useCORSPreflightFlag: false,
      credentials: 'same-origin',
      useCredentials: false,
      cache: 'default',
      redirect: 'follow',
      integrity: '',
      cryptoGraphicsNonceMetadata: '',
      parserMetadata: '',
      reloadNavigation: false,
      historyNavigation: false,
      userActivation: false,
      taintedOrigin: false,
      redirectCount: 0,
      responseTainting: 'basic',
      preventNoCacheCacheControlHeaderModification: false,
      done: false,
      timingAllowFailed: false,
      headersList: [HeadersList],
      urlList: [Array],
      url: [URL]
    },
    [Symbol(signal)]: AbortSignal { aborted: false },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
d:\Documents\GitHub\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:53
    throw new Error('Failed to ingest your data');
          ^


[Error: Failed to ingest your data]

Node.js v18.14.2
 ELIFECYCLE  Command failed with exit code 1.

**Comment by TextToSQL** [comment]
fixed it already. thanks

**Comment by louis-sanna-eki** [comment]
@TextToSQL how did you fix it?

**Comment by TextToSQL** [comment]
i 've spent hours 1) trying to understand where the problem is, 2) consulting with chat gpt :-) , and 3) tailoring the code here and there. i 've also updated several packages. to be very honest, i am not 100 % sure what helped exactly. as a first step, i 'd recommend you install VS studio , take a look at problems tab (it would say in which part of the code there is an issue), make sure to install all packages as per Mayo instructions. I think most important is to make sure PineCone client is up to date. I hope this helps.

**Comment by TextToSQL** [comment]
sorry, another first step is to look at the console and see if the text is actually splitting and embedding works. if yes, than the issue is likely with pinecone client

**Comment by TextToSQL** [comment]
another one i forgot to mention - make sure to change the gpt model if you don't have access to gpt4 yet. i've changed mine to gpt3.5turbo

**Comment by louis-sanna-eki** [comment]
@TextToSQL thx! I have a very strange "PineconeClient: Project name not set. Call init() first." error, despite the official doc no require it.

https://www.npmjs.com/package/@pinecone-database/pinecone

<img width="576" alt="Screenshot 2023-03-26 at 16 21 02" src="https://user-images.githubusercontent.com/85956496/227782146-e30896dc-fc72-441d-be80-1ca249665190.png">

**Comment by TextToSQL** [comment]
i thought we are initializing it somewhere. my best advice - ask chatgpt about this particular error. and also look at the 'problems' tab in VS

**Comment by TextToSQL** [comment]
did pinecone-client install ok?

**Comment by louis-sanna-eki** [comment]
https://github.com/pinecone-io/pinecone-ts-client/issues/12

**Comment by louis-sanna-eki** [comment]
So I finally managed to make it work.

The pinecode lib use the projectName to build the url, but so you have to set on the object. The projectName can be found in the pinecode interface.

// Pinecode lib
<img width="967" alt="Screenshot 2023-03-26 at 17 07 21" src="https://user-images.githubusercontent.com/85956496/227785006-a70c7284-9733-41d5-a06d-5977ec4c6486.png">
// Pinecode interface with name
<img width="1545" alt="Screenshot 2023-03-26 at 17 07 53" src="https://user-images.githubusercontent.com/85956496/227785009-31183bcc-f005-4f4a-a005-b04ead28b6f9.png">
// Your code where you set the projectName
<img width="701" alt="Screenshot 2023-03-26 at 17 07 32" src="https://user-images.githubusercontent.com/85956496/227785008-5b3497d0-a7e2-4a45-b567-357119181f00.png">


I have no idea how it works for everyone else.

**Comment by mayooear** [comment]
> another one i forgot to mention - make sure to change the gpt model if you don't have access to gpt4 yet. i've changed mine to gpt3.5turbo

This is a major cause of issues. Many people attempt to use gpt-4 when they don't yet have access.

**Comment by mayooear** [comment]
> So I finally managed to make it work.
> 
> The pinecode lib use the projectName to build the url, but so you have to set on the object. The projectName can be found in the pinecode web UI.
> 
> // Pinecode lib <img alt="Screenshot 2023-03-26 at 17 07 21" width="967" src="https://user-images.githubusercontent.com/85956496/227785006-a70c7284-9733-41d5-a06d-5977ec4c6486.png"> // Pinecode interface with name <img alt="Screenshot 2023-03-26 at 17 07 53" width="1545" src="https://user-images.githubusercontent.com/85956496/227785009-31183bcc-f005-4f4a-a005-b04ead28b6f9.png"> // Your code where you set the projectName <img alt="Screenshot 2023-03-26 at 17 07 32" width="701" src="https://user-images.githubusercontent.com/85956496/227785008-5b3497d0-a7e2-4a45-b567-357119181f00.png">
> 
> I have no idea why it works for everyone else.

strange why it doesn't work for you without setting a projectname.

**Comment by felipeotarola** [comment]
> So I finally managed to make it work.
> 
> The pinecode lib use the projectName to build the url, so you have to set on the object. The projectName can be found in the pinecode web UI.
> 
> // Pinecode lib <img alt="Screenshot 2023-03-26 at 17 07 21" width="967" src="https://user-images.githubusercontent.com/85956496/227785006-a70c7284-9733-41d5-a06d-5977ec4c6486.png"> // Pinecode interface with name <img alt="Screenshot 2023-03-26 at 17 07 53" width="1545" src="https://user-images.githubusercontent.com/85956496/227785009-31183bcc-f005-4f4a-a005-b04ead28b6f9.png"> // Your code where you set the projectName <img alt="Screenshot 2023-03-26 at 17 07 32" width="701" src="https://user-images.githubusercontent.com/85956496/227785008-5b3497d0-a7e2-4a45-b567-357119181f00.png">
> 
> I have no idea why it works for everyone else.

Awesome thanks for this solution I was also experiencing this, adding the pinecone.projectName to the initPinectode function got me  to the next problem, that was causing by the basePath in the pinecone library, the concat didn't work for my url so I just hardcoded and it worked.

**Comment by okmike** [comment]
> error [Error: Network Error] { config: { transitional: { silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false }, adapter: [AsyncFunction: fetchAdapter], transformRequest: [ [Function: transformRequest] ], transformResponse: [ [Function: transformResponse] ], timeout: 0, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, maxBodyLength: -1, validateStatus: [Function: validateStatus], headers: { Accept: 'application/json, text/plain, _/_', 'Content-Type': 'application/json', 'User-Agent': 'OpenAI/NodeJS/3.2.1', Authorization: 'Bearer sk-XXXXX'(here is the openai api key) }, method: 'post',
> 
> url: 'https://api.openai.com/v1/embeddings' }, code: 'ERR_NETWORK', request: Request { [Symbol(realm)]: { settingsObject: [Object] }, [Symbol(state)]: { method: 'POST', localURLsOnly: false, unsafeRequest: false, body: [Object], client: [Object], reservedClient: null, replacesClientId: '', window: 'client', keepalive: false, serviceWorkers: 'all', initiator: '', destination: '', priority: null, origin: 'client', policyContainer: 'client', referrer: 'client', referrerPolicy: '', mode: 'cors', useCORSPreflightFlag: false, credentials: 'same-origin', useCredentials: false, cache: 'default', redirect: 'follow', integrity: '', cryptoGraphicsNonceMetadata: '', parserMetadata: '', reloadNavigation: false, historyNavigation: false, userActivation: false, taintedOrigin: false, redirectCount: 0, responseTainting: 'basic', preventNoCacheCacheControlHeaderModification: false, done: false, timingAllowFailed: false, headersList: [HeadersList], urlList: [Array], url: [URL] }, [Symbol(signal)]: AbortSignal { aborted: false }, [Symbol(headers)]: HeadersList { cookies: null, [Symbol(headers map)]: [Map], [Symbol(headers map sorted)]: null } }, response: undefined, isAxiosError: true, toJSON: [Function: toJSON] } d:\Documents\GitHub\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:53 throw new Error('Failed to ingest your data'); ^
> 
> [Error: Failed to ingest your data]
> 
> Node.js v18.14.2  ELIFECYCLE  Command failed with exit code 1.

Exact same problem here. Keep getting the Network Error message. But I have Clash proxy running at the same time, not sure if the Clash casues network conflicts.

**Comment by okmike** [comment]
I tried to change Clash proxy mode to Global、Rule、Direct multiple times, and the Network Error message keeps appearing.

**Comment by devmuhammadasad** [comment]
![image](https://user-images.githubusercontent.com/104306074/228355070-dd11ab63-f8a3-44e8-b4cd-948708ebf28f.png)


Exact same problem here. Someone, please resolve this...

**Comment by yudidina** [comment]
> 

Me, too

**Comment by yudidina** [comment]
> I tried to change Clash proxy mode to Global、Rule、Direct multiple times, and the Network Error message keeps appearing.

Me, too, damn

**Comment by okmike** [comment]
> > > 另一个我忘记提到的 - 如果您还没有访问 gpt4，请确保更改 gpt 模型。我已经把我的改成了 gpt3.5turbo
> > 
> > 
> > 这是造成问题的主要原因。许多人在还没有访问权限时尝试使用 gpt-4。
> 
> 已经是gpt3.5turbo了 T T文本也在分段，确实不明白是什么问题，pinecode需要修改么？我看他们上面提到了pinecone-client，是需要装这个？

如果用Clash科学上网的话，可以看下我的回复

**Comment by zina0** [comment]
> 我也遇到这个问题，也有科学上网了，但是不行，显然pinecone那边也没办法读入数据，有解决的话麻烦说一下

**Comment by okmike** [comment]
> 
这我就不清楚了，我是直接把TUN mode开关打开就行了。然后把UWP loopback里能选的都选上了。

**Comment by okmike** [comment]
> > > > > 另一个我忘记提到的 - 如果您还没有访问 gpt4，请确保更改 gpt 模型。我已经把我的改成了 gpt3.5turbo
> > > > 
> > > > 
> > > > 这是造成问题的主要原因。许多人在还没有访问权限时尝试使用 gpt-4。
> > > 
> > > 
> > > 已经是gpt3.5turbo了 T T文本也在分段，确实不明白是什么问题，pinecode需要修改么？我看他们上面提到了pinecone-client，是需要装这个？
> > 
> > 
> > 如果用Clash科学上网的话，可以看下我的回复
> 
> awsome, seems i can get to pinecone, but new 
problem~~~~creating vector store... error [TypeError: documents.map is not a function] d:\Documents\GitHub\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:44 throw new Error('Failed to ingest your data'); ^
> 
> [Error: Failed to ingest your data]

试试安装pico-client？

> > > > > 另一个我忘记提到的 - 如果您还没有访问 gpt4，请确保更改 gpt 模型。我已经把我的改成了 gpt3.5turbo
> > > > 
> > > > 
> > > > 这是造成问题的主要原因。许多人在还没有访问权限时尝试使用 gpt-4。
> > > 
> > > 
> > > 已经是gpt3.5turbo了 T T文本也在分段，确实不明白是什么问题，pinecode需要修改么？我看他们上面提到了pinecone-client，是需要装这个？
> > 
> > 
> > 如果用Clash科学上网的话，可以看下我的回复
> 
> awsome, seems i can get to pinecone, but new problem~~~~creating vector store... error [TypeError: documents.map is not a function] d:\Documents\GitHub\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:44 throw new Error('Failed to ingest your data'); ^
> 
> [Error: Failed to ingest your data]

试试安装pico-client？

**Comment by GrantRomero** [comment]
> > So I finally managed to make it work.
> > The pinecode lib use the projectName to build the url, but so you have to set on the object. The projectName can be found in the pinecode web UI.
> > // Pinecode lib <img alt="Screenshot 2023-03-26 at 17 07 21" width="967" src="https://user-images.githubusercontent.com/85956496/227785006-a70c7284-9733-41d5-a06d-5977ec4c6486.png"> // Pinecode interface with name <img alt="Screenshot 2023-03-26 at 17 07 53" width="1545" src="https://user-images.githubusercontent.com/85956496/227785009-31183bcc-f005-4f4a-a005-b04ead28b6f9.png"> // Your code where you set the projectName <img alt="Screenshot 2023-03-26 at 17 07 32" width="701" src="https://user-images.githubusercontent.com/85956496/227785008-5b3497d0-a7e2-4a45-b567-357119181f00.png">
> > I have no idea why it works for everyone else.
> 
> strange why it doesn't work for you without setting a projectname.

I addded the project name and am getting this error still 
![Capture](https://user-images.githubusercontent.com/122701091/228643592-e009c3b9-d69c-4b2b-a72b-455eb22cabbd.PNG)

**Comment by hipnologo** [comment]
I am facing similar problem; after running `npm run ingest` and get a successful message, I checked Pinecone index info and got a namespace "books" with a total vectors of 309. However, after initializing the app `pnpm run dev` and typing a question, I see the error below in the logs and in the client page an empty response.

```
PineconeClient: Error getting project name: TypeError: fetch failed
error - [Error: PineconeClient: Project name not set. Call init() first.] {
  page: '/api/chat'
}
wait  - compiling /_error (client and server)...
```
Pinecode and config files are matching README instructions.

**Comment by naticio** [comment]
same error for me...
<img width="805" alt="image" src="https://user-images.githubusercontent.com/34293050/229326421-365c0598-8f21-4399-bf05-56b626fdf76a.png">

**Comment by naticio** [comment]
> initPinectode

thanks, I did this but now I get a new error :(
Error: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response]

**Comment by stephanmingoes** [comment]
![image](https://user-images.githubusercontent.com/60485782/229618337-750b5c77-c9f7-4ec1-8ca3-dd818bd43d93.png)

Is anyone else getting status code 429 aka "too many requests"?

**Comment by Dasheverless** [comment]
> ![image](https://user-images.githubusercontent.com/60485782/229618337-750b5c77-c9f7-4ec1-8ca3-dd818bd43d93.png)
> 
> Is anyone else getting status code 429 aka "too many requests"?

you can use python chatgpt api demo to check your problem. I fix this issue by setting up a payment method in my openai api page.

**Comment by cklingspor** [comment]
With regard to the 429. Check out [here](https://stackoverflow.com/questions/75041580/openai-api-giving-error-429-too-many-requests). 

> The reason was that I created my API key BEFORE converting my OpenAI account to paid (adding credit card). Doesn't matter if you only upgrade, you also need to create a new api key entirely. I created another API key AFTER I added my credit card and it worked fine!

This helped me as well

**Comment by larri-eng** [comment]
I am getting the same error. Any insights?

  request: Request {
    [Symbol(realm)]: { settingsObject: [Object] },
    [Symbol(state)]: {
      method: 'POST',
      localURLsOnly: false,
      unsafeRequest: false,
      body: [Object],
      client: [Object],
      reservedClient: null,
      replacesClientId: '',
      window: 'client',
      keepalive: false,
      serviceWorkers: 'all',
      initiator: '',
      destination: '',
      priority: null,
      origin: 'client',
      policyContainer: 'client',
      referrer: 'client',
      referrerPolicy: '',
      mode: 'cors',
      useCORSPreflightFlag: false,
      credentials: 'same-origin',
      useCredentials: false,
      cache: 'default',
      redirect: 'follow',
      integrity: '',
      cryptoGraphicsNonceMetadata: '',
      parserMetadata: '',
      reloadNavigation: false,
      historyNavigation: false,
      userActivation: false,
      taintedOrigin: false,
      redirectCount: 0,
      responseTainting: 'basic',
      preventNoCacheCacheControlHeaderModification: false,
      done: false,
      timingAllowFailed: false,
      headersList: [HeadersList],
      urlList: [Array],
      url: [URL]
    },
    [Symbol(signal)]: AbortSignal { aborted: false },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  },
  response: {
    ok: false,
    status: 401,
    statusText: 'Unauthorized',
    headers: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    config: {
      transitional: [Object],
      adapter: [AsyncFunction: fetchAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
