### ISSUE TITLE
please teach us to deploy

### ISSUE THREAD

**Issue by text2sql** [mayooear/gpt4-pdf-chatbot-langchain#62]
Hey @mayooear thank you so much for your incredible work and sharing it with the world. 
For those of us, who are not very experienced, can you pls share your recommendations with step-by-step how to deploy it on vercel or any other platform? Vercel in my case keeps throwing tantrums. 
Thank you!

**Comment by louis-sanna-eki** [comment]
@TextToSQL you should need to need to connect vercel to your github repo and add the env variables. And that's all.

That being said: there's also a problem with the streaming of the answer: it's lost when deployed, and I think we need to convert it to an edge function.

https://vercel.com/templates/svelte/watch-this

**Comment by TextToSQL** [comment]
I keep getting this error when trying to deploy 
Failed to compile.
./config/pinecone.ts:5:12
Type error: '=' expected.
  3 |  */
  4 | 
> 5 | import node-fetch; 
    |            ^
  6 | 
  7 | const PINECONE_INDEX_NAME = 'chat-pdf';
  8 | 
Error: Command "pnpm run build" exited with 1
BUILD_UTILS_SPAWN_1: Command "pnpm run build" exited with 1

**Comment by TextToSQL** [comment]
what do you have in environment settings on vercell?

**Comment by louis-sanna-perso** [comment]
@TextToSQL the 3 ones shown in .env.example

And there should be no import your config file, see example: https://github.com/mayooear/gpt4-pdf-chatbot-langchain/blob/main/config/pinecone.ts

**Comment by TextToSQL** [comment]
figured it out ., thank you. deployed!

**Comment by mayooear** [comment]
> figured it out ., thank you. deployed!

@louis-sanna-perso thank you for providing guidance.

@TextToSQL  can you share your steps towards deployment for future users?

**Comment by TextToSQL** [comment]
The streaming effect is not working for me either. I need to wait for 3-4 sec and then the whole paragraph appears. Is there any way to fix it for non-technical folks?

**Comment by louis-sanna-eki** [comment]
@TextToSQL you have to deploy it on another provider, Fly for instance.

https://twitter.com/mayowaoshin/status/1640128383051767808

**Comment by danielcwq** [comment]
hey @mayooear thanks for creating this! currently having a trouble with runtime error - after deploying on vercel, it keeps giving me a post 504 error - would the problem be vercel? or is there something wrong with my code 
![Screenshot 2023-03-27 at 12 07 43 PM](https://user-images.githubusercontent.com/75194564/227838442-93ff5236-05b7-4087-9aba-d42667446089.png)

**Comment by mayooear** [comment]
> hey @mayooear thanks for creating this! currently having a trouble with runtime error - after deploying on vercel, it keeps giving me a post 504 error - would the problem be vercel? or is there something wrong with my code ![Screenshot 2023-03-27 at 12 07 43 PM](https://user-images.githubusercontent.com/75194564/227838442-93ff5236-05b7-4087-9aba-d42667446089.png)

Check your deployment logs on the Vercel dashboard. I suspect it's related to serverless timeout issues.

**Comment by tiwentichat** [comment]
> TextToSQL

hi dude, i'm also tring to deploy it to vercel, would you like to share how did you make it?

The steps i did are like this but seems no vectors in pinecone.

1, made new project, via third party  and paste this link https://github.com/mayooear/gpt4-pdf-chatbot-langchain

2, creat and wait until it's deployed,

3, add openaiapikey/pineconekey,evnironment,indexname as .env.example, in vercel project Environment Variables

4,redeploy the project

then i could talk with it and get response, but the chatbot's answer does not refer to the docs, 

it's like this: what is the legal case about? bot answer:   Hmm, I'm not sure. The extracted parts of the document provided do not give enough information to determine the overall content of the document. Can you provide more context or a specific section of the document to focus on?

and in pinecone, i could not find any vectors

wish for your kindly help

**Comment by notflip** [comment]
@mayooear I'm also running into the 504 error once deployed on Vercel, have you found a solution?

**Comment by urltron8617** [comment]
Deployed using Netlify APP

1. UI is loaded without Images 
2. API call is not working

I Got response like :::
{errorType: "ReferenceError",…}
errorMessage
: 
"module is not defined in ES module scope\nThis file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains \"type\": \"module\". To treat it as a CommonJS script, rename it to use the '.cjs' file extension."
errorType
: 
"ReferenceError"
trace
: 
["ReferenceError: module is not defined in ES module scope",…]


**If someone know something :)**

**Comment by headdaotw** [comment]
I'm also running into the 504 error

**Comment by AyoCodess** [comment]
Is there a solution to enable us to deploy this on vercel without upgrading to pro?

**Comment by TextToSQL** [comment]
i deployed on render. worked fine.

**Comment by AyoCodess** [comment]
> i deployed on render. worked fine. 

Did you use the "web service" option?

**Comment by TextToSQL** [comment]
Yes

**Comment by TextToSQL** [comment]
add all the keys to the “Environment” and also add the commands as in the picture 
￼

**Comment by TextToSQL** [comment]
<img width="1092" alt="Screenshot 2023-04-10 at 12 36 06 PM" src="https://user-images.githubusercontent.com/127912312/230947790-cc7fe9e4-5a94-4339-8387-b656fb66e6ff.png">

**Comment by AyoCodess** [comment]
Thank you, i worked it out in the end but this will help others when it comes to deployment.

**Comment by alexndrvega** [comment]
> @texttosql I was able to deploy based on your info, thank you. I'm able to ask a question, and I can see that it logs some sort of result, but the answer is just blank. What can I look for? FYI, I trained it with my own data, and I did not find the start command you mentioned above.
> 
> ![2023-04-11 08_38_14-Window](https://user-images.githubusercontent.com/127154082/231076710-953d99cb-bf17-4d2a-a971-e2f6a0e57cf8.png)

Make sure you change the modelName located in utils>makechain.ts to gpt-3.5-turbo 

This fixed the issue for me as I was getting empty outputs. I don't have access to gpt-4 API yet.
