### ISSUE TITLE
Ability to have different QA_PROMPT to choose from

### ISSUE THREAD

**Issue by revbin** [mayooear/gpt4-pdf-chatbot-langchain#64]
Hi

can we have the ability to have  Multiple embedded QA_PROMPT for different use cases

like this project : https://github.com/jas3333/gptchat_pinecone.

regards

**Comment by mayooear** [comment]
I don't see QA_PROMPT in that repo

**Comment by revbin** [comment]
there is juste check : https://github.com/jas3333/gptchat_pinecone/blob/master/data/personas.js
