### ISSUE TITLE
Error getting project name: Fetch from Pinecone /whoami

### ISSUE THREAD

**Issue by felipeotarola** [mayooear/gpt4-pdf-chatbot-langchain#72]
I'm having trouble to connect to the pinecone index, 
When I run the project and types in a question I get this error :

PineconeClient: Error getting project name: FetchError: request to https://controller.documents-2xxxxxx.svc.us-central1-gcp.pinecone.io.pinecone.io/actions/whoami 

By reading another issue I found out that in the node_modules/@pinecone-database there is a switch in the library that creates this variable 
whoami = "".concat(controllerPath, "/actions/whoami");
![image](https://user-images.githubusercontent.com/5517674/228313252-e843d568-e808-4380-82cd-8ba96dba6c68.png)

If I remove the concat and hardcode the path, then it actually works, but not really ideal when rebuilding the node and deploying.

any one else having this problem? or know how to fix it.
Thanks in advance

**Comment by felipeotarola** [comment]
Maybe I have just misunderstand what should be in the PINECONE_INDEX_NAME?

is it documents? or the entire url? 
![image](https://user-images.githubusercontent.com/5517674/228342486-5705bb87-5fb1-47bb-85a4-e0590c2ecab1.png)

**Comment by pablosr11** [comment]
Its the index name. Can be whatever you want: https://docs.pinecone.io/docs/manage-indexes

**Comment by felipeotarola** [comment]
Thank you.  I still have problem though. 
I have found out this, that in the pinecone library it creates a basePath in the  PineconeClient.prototype.Index

If I hardcode the basepath like this
basePath: "https://documents-54978f2.svc.us-east1-gcp.pinecone.io",  it works to ingest, but the concat creates a path  that looks like this

https://pdf-test-54978f2.svc.documents-54978f2.svc.us-east1-gcp.pinecone.io
(basePath: "https://".concat(index, "-").concat(this.projectName, ".svc.").concat(this.environment, ".pinecone.io"),)


To continue with some of my problems, 
In the pinecone-client, I need to specify the pinecone.projectName in the initPinecone function like this

![image](https://user-images.githubusercontent.com/5517674/228463769-e3e4e0da-cc14-4e48-967e-11b895b01482.png)

otherwise I get this error 
Call init() first.

So that indeed is manipulating the concat, but I have no other solution on how to fix the init problem.

**Comment by felipeotarola** [comment]
Thank you, I have tried that, but will try again 
I have even upgraded for payment so I can try different ones  :(

btw.
if the url looks like this 
https://testy-54978f2.svc.us-east1-gcp.pinecone.io

is this the correct env and namespace?

PINECONE_ENVIRONMENT=testy-54978f2.svc.us-east1-gcp
PINECONE_INDEX_NAME=testy

const PINECONE_NAME_SPACE = '54978f2';

Could this mess with the concat in the lib?

**Comment by pbshgthm** [comment]
Were you able to fix this error?

**Comment by felipeotarola** [comment]
Unfortnally no.
But I can bypass the error if I do changes directly in the node package

nodu_modules
@pineconde-database\pincone\dist\pinecone-generated-ts-fetch\index.js

in the bottom you have a function called 
PineconeClient.prototype.Index = function (index) {

and hardcode the basePath insted of the concat. 

in that way I get the application to work, but ofc this does not work when going in production.

**Comment by pbshgthm** [comment]
Turns out the problem for me was the API Keys and Env were not exported properly. Fixing it solved the issue for me.

**Comment by GrantRomero** [comment]
> Turns out the problem for me was the API Keys and Env were not exported properly. Fixing it solved the issue for me.

Can you explain how you fixed it?

**Comment by pbshgthm** [comment]
In my case I hadn't used dotenv and so process.env didn't work. Try console.log'ing the env variables and make sure they are exposed to the node runtime.

**Comment by felipeotarola** [comment]
found out that the problem was the my env file, when I fixed that I could ingest. 

env file template

![image](https://user-images.githubusercontent.com/5517674/229345967-a9c6a1da-a2e9-4e20-8fc2-ef86da1cd46f.png)

PINECONE_ENVIRONMENT="eu-west1-gcp"
PINECONE_INDEX_NAME="indexname"
PINECONE_API_KEY = "0000000-0000-42a9-901b-123456788"

**Comment by Rajveermathur** [comment]
I was suffering with the same issue and after seeing much of stackoverflow and forums I saw changing the version will do the work, but I was using the latest one (v0.1.6).
**What I did:** I just re-install the module into my project and it worked. (npm install)

**Comment by Victor-Timi** [comment]
Here was how i solved mine, i changed my PINECONE_NAMESPACE  to the name I gave to my API key
