### ISSUE TITLE
Racking My Brain - Failing To Ingest

### ISSUE THREAD

**Issue by rancor13** [mayooear/gpt4-pdf-chatbot-langchain#73]
Have read the documentation over, and over, and over... Have created new API keys on OpenAI / Pinecone. Have double, and triple checked the name space, index name, and environment are 100% correct. 
![image](https://user-images.githubusercontent.com/129128129/228333966-c1a6ec7f-210f-4a26-948e-bbe85f6f2fa2.png)

 **********************************************************************
** Visual Studio 2022 Developer PowerShell v17.5.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
PS C:\Users\Randall Cornett\Source\Repos\mayooear\gpt4-pdf-chatbot-langchain>     url: 'https://api.openai.com/v1/embeddings'
>>     },
>>     request: Request {
>>       [Symbol(realm)]: [Object],
>>       [Symbol(state)]: [Object],
>>       [Symbol(signal)]: [AbortSignal],
>>       [Symbol(headers)]: [HeadersList]
>>     },
>>     data: { error: [Object] }
>>   },
>>   isAxiosError: true,
>>   toJSON: [Function: toJSON]
>> }
>> c:\Users\Randall Cornett\source\repos\mayooear\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:49
>>     throw new Error('Failed to ingest your data');
>>           ^
>>
>>
>> [Error: Failed to ingest your data]
>>

Anything to help me fix this would be greatly appreciated. Spent like 6 hours last night and made like no progress.

**Comment by toniseldr** [comment]
are you using gpt-4?

**Comment by rancor13** [comment]
Have used them both (I have GPT-4).. still no avail. It splits the documents, etc etc. Everything looks fine up until the very send when creating the vector store then bam.. Failed to ingest the data. 

Have tried 3x different open AI API keys, Multiple (paid for pine cone) environments, have watched the video 100x. Updaded any sort of plugin / update that VM studio told me in terms of code. It's getting hung up on the last part. Frustrating.

**Comment by rancor13** [comment]
![image](https://user-images.githubusercontent.com/129128129/228420899-25889051-2897-4312-b8ee-ca4dd294fd0d.png)

**Comment by axr6077** [comment]
Ran into same issue. Fixed it by making sure to initialize an index in Pinecone Dashboard and making sure the namespaces match the one in the dashboard. You can find the namespace under config/pinecone.ts

`const PINECONE_NAME_SPACE = <make sure it is same as dashboard>`

**Comment by rancor13** [comment]
Really appreciate the response.. but I have no name space... in Pinecone. 
![image](https://user-images.githubusercontent.com/129128129/228435266-5e411453-24bc-4f31-858f-d5e4ad26857a.png)

**Comment by rancor13** [comment]
CHATGPT says I need to ingest data into it first.. but how can I ingest if it always fails? Thank you for your help.

**Comment by pablosr11** [comment]
The latest error you sent has a status code 429 ~~ pinecone complaining about receiving too many requests. Could you try with a single doc to discard this being the issue?

**Comment by rancor13** [comment]
Yep, using the default PSD provided with the clone just for testing sake. So only 1 pdf.

**Comment by rancor13** [comment]
> Ran into same issue. Fixed it by making sure to initialize an index in Pinecone Dashboard and making sure the namespace in pinecone.ts match the one in the dashboard (you can find it under Index Info). You can find the namespace under config/pinecone.ts
> 
> `const PINECONE_NAME_SPACE = <make sure it is same as dashboard>`
> 
> Edit: Initialize index and confirm its 'Ready' before running ingest script.

Managed to get an index through like the query portion and edit of Pinecones website. Here is where I'm at now. 

![image](https://user-images.githubusercontent.com/129128129/228439894-bc16b087-8489-44d6-b865-e2ea9b69799b.png)

with that  on pinecone as well... 
![image](https://user-images.githubusercontent.com/129128129/228440045-27b211f1-3645-4f77-89ad-ccb575ac55c3.png)


Still failing to ingest.

**Comment by pablosr11** [comment]
Line 9 references amcbot2 instead of pinecone_index_name. Is that it?

**Comment by rancor13** [comment]
Nope, fixed it I was re reading my post :( 
![image](https://user-images.githubusercontent.com/129128129/228445019-f2befca5-a639-475c-a597-3698a65defdb.png)

**Comment by toniseldr** [comment]
I faced the same problem yesterday...try one thing: delete your pinecone project and create another one, not the index, the whole project. When creating a new one, choose another environment and create a new index.

**Comment by ttu-nguyen** [comment]
I hit exactly the same error.

**Comment by hmzakhalid** [comment]
Hey @rancor13, I just fixed this same error. The error is due to the multiple OPENAI API keys in the environment.
apparently the env variable in `env` from the project gets overwritten by systems env variable. 
So just check your Systems Environment variable in Windows and delete it or change it to the new API key. 
To check, you can use the following commands
Windows:
`echo %OPENAI_API_KEY%`
Linux:
`echo OPENAI_API_KEY`
Mac:
`printenv | grep OPENAI_API_KEY`

**Comment by Lionardo** [comment]
I am also getting the error:
```
creating vector store...
error [Error: PineconeClient: Error calling upsert: Error: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response]
/Users/lionardo/Documents/Sites/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:44
    throw new Error('Failed to ingest your data');
          ^


[Error: Failed to ingest your data]
```
I have the Name space set and I am loading only 1 pdf.

**Comment by bschleter** [comment]
@Lionardo mind telling me what you mean or where you place the curl command? I had the same error this morning and yesterday. All namespaces and all that labeled, pinecone index ready etc.

**Comment by GrantRomero** [comment]
I am still running into this error: [Error: Failed to ingest your data]. I have triple checked all of my api keys, I have deleted and created 3 different projects and indexes on pinecone with different environments. I only have one active openai api key. I have tried to do this on both my windows pc and my Mac and I am running into the same error.

**Comment by rancor13** [comment]
> Hey @rancor13, I just fixed this same error. The error is due to the multiple OPENAI API keys in the environment. apparently the env variable in `env` file from the project gets overwritten by systems env variable. So just check your Systems Environment variable and delete it or change it to the correct API KEY. To check, you can use the following commands
> 
> ### Windows:
> `echo %OPENAI_API_KEY%`
> 
> ### Linux:
> `echo OPENAI_API_KEY`
> 
> ### Mac:
> `printenv | grep OPENAI_API_KEY`

Was really excited this would work.. but nope.  When I run the windows command in terminal it just spits back the correct API key I'm supposed to be using... so that's confusing. Dang.. thought this would work..

Have  now created a whole new project with new index and new, different environment etc as suggested. Still the same exact error. Failed to ingest.. to many requests : /

**Comment by rancor13** [comment]
> I hit exactly the same error. still stuck with 429 too many requests error. tried only one pdf doc but still had the error. how did you manage to overcome this error @rancor13 ?

Haven't. Tried every suggestion listed in the thread.

**Comment by hmzakhalid** [comment]
> > Hey @rancor13, I just fixed this same error. The error is due to the multiple OPENAI API keys in the environment. apparently the env variable in `env` file from the project gets overwritten by systems env variable. So just check your Systems Environment variable and delete it or change it to the correct API KEY. To check, you can use the following commands
> > ### Windows:
> > `echo %OPENAI_API_KEY%`
> > ### Linux:
> > `echo OPENAI_API_KEY`
> > ### Mac:
> > `printenv | grep OPENAI_API_KEY`
> 
> Was really excited this would work.. but nope. When I run the windows command in terminal it just spits back the correct API key I'm supposed to be using... so that's confusing. Dang.. thought this would work..
> 
> Have now created a whole new project with new index and new, different environment etc as suggested. Still the same exact error. Failed to ingest.. to many requests : /

Then have you checked the error code?
The too many requests. Is it from openai or pinecone?
The solution I provided was for openai 401 error. Which means the api key is incorrect.
If you can provide the complete output of the error you get. It would help me understand and I can maybe help you from there.

**Comment by focusai** [comment]
Sure the cause of my error is less common than for most as I'm new to this, but I did not have langchain installed. One to try pip install langchain

**Comment by linwentao-hexin** [comment]
same error... is it from openai or pinecone...

i have checked pinecone PINECONE_NAME_SPACE and PINECONE_INDEX_NAME
![image](https://user-images.githubusercontent.com/105496554/229016501-f2f0da57-7215-444a-adcf-f5dd6e927a9a.png)

**Comment by LvisWang** [comment]
hey @rancor13 , are you using a proxy like clash?

**Comment by 15392778677** [comment]
> hey @rancor13 , are you using a proxy like clash?

I meet the same error and I also sue proxy as clash ,but  it also can not work correctly

**Comment by anaszil** [comment]
@rancor13, I encountered the same error and discovered that it was caused by my OpenAI account. Using the API requires payment for each request. In order to resolve the issue, I added a credit card to my account and now it works.

**Comment by discolando** [comment]
@rancor13 I came here just to say the exact same thing as @anaszil. I kept getting a 429 response no matter what, and after messing around with a separate Python library, I realized that the 429 was coming from OpenAI, and adding a payment method to my account immediately resolved the issue - I'm able to ingest data now and get responses from the chat.

**Comment by obaeyaert** [comment]
If you experience a 429 error, just create a new user for chatGPT (another google account for exemple).
Generate a new API key.
Replace your old one.
Solved my problem instantly.

`creating vector store...
ingestion complete`

**Comment by TheBossDragon** [comment]
Wow, thanks to all of you for going through this. Following this instantly solved my errors.

**Comment by prophesy604** [comment]
hi, i'm getting the 429 error, i have a payment card on openai 

i don't know how to create the namespace though

only 1 api key shows up for openai

any thoughts on how to resolve? appreciate any help, thanks
