### ISSUE TITLE
Don't support Chinese

### ISSUE THREAD

**Issue by boogunote** [mayooear/gpt4-pdf-chatbot-langchain#76]
I take this pdf file. http://www.zstack.io/docs/4.6.0/pdf-cn/PD4906%20ZStack%20Cloud%20V4.6.0%20%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94%EF%BC%88FAQ%EF%BC%89.pdf

After ingest, I tried some queries. The answer is blank. But I can see correct response in the console log.

How to solve that?

**Comment by okmike** [comment]
Same problem here. What should I do if I have a file contains more than one language?  Should I change the QA_PROMPT to Chinese if I want to ask and answer all in Chinese? Thanks for answering the question.

**Comment by okmike** [comment]
I change the prompt to chinese and it works. 
![image](https://user-images.githubusercontent.com/37909931/228628399-8b9baedb-01af-406e-a099-e6cd5497dddc.png)

**Comment by digitalboy** [comment]
很赞！支持中文！

**Comment by digitalboy** [comment]
> I change the prompt to chinese and it works. ![image](https://user-images.githubusercontent.com/37909931/228628399-8b9baedb-01af-406e-a099-e6cd5497dddc.png)

很不错啊！

**Comment by userAmani** [comment]
Just add 'You reply in Chinese' to the original description

**Comment by smallnine9** [comment]
@boogunote 兄弟，你在npm run ingest的时候没有网络错误吗？请教怎么搞的
