### ISSUE TITLE
PINECONE_NAME_SPACE

### ISSUE THREAD

**Issue by revbin** [mayooear/gpt4-pdf-chatbot-langchain#80]
Hi

it is possible to not have PINECONE_NAME_SPACE name configured in config file.
the reasons its i already have a pinecone DB with Vectors without namespace.

regards

**Comment by janek** [comment]
Based on https://docs.pinecone.io/docs/namespaces, it seems like if you're just trying to get things to work, it doesn't matter what PINECONE_NAME_SPACE is:

> A destination namespace can be specified when vectors are upserted. If the namespace doesn't exist, it is created implicitly.

> When you don't specify a namespace name for an operation, Pinecone uses the default namespace name of "" (the empty string).

If you provide any string, Pinecone will use that. If you don't provide anything, it will use a default.

It would be good if this repo's description made that more explicit, it was unclear for me too

**Comment by revbin** [comment]
thx for information . i will try again to make it work without configured namespace.

**Comment by mayooear** [comment]
> thx for information . i will try again to make it work without configuring namespace.


> Based on https://docs.pinecone.io/docs/namespaces, it seems like if you're just trying to get things to work, it doesn't matter what PINECONE_NAME_SPACE is:
> 
> > A destination namespace can be specified when vectors are upserted. If the namespace doesn't exist, it is created implicitly.
> 
> > When you don't specify a namespace name for an operation, Pinecone uses the default namespace name of "" (the empty string).
> 
> If you provide any string, Pinecone will use that. If you don't provide anything, it will use a default.
> 
> It would be good if this repo's description made that more explicit, it was unclear for me too

Why would you want to use this without a namespace?

**Comment by revbin** [comment]
> > thx for information . i will try again to make it work without configuring namespace.
> 
> > Based on https://docs.pinecone.io/docs/namespaces, it seems like if you're just trying to get things to work, it doesn't matter what PINECONE_NAME_SPACE is:
> > > A destination namespace can be specified when vectors are upserted. If the namespace doesn't exist, it is created implicitly.
> > 
> > 
> > > When you don't specify a namespace name for an operation, Pinecone uses the default namespace name of "" (the empty string).
> > 
> > 
> > If you provide any string, Pinecone will use that. If you don't provide anything, it will use a default.
> > It would be good if this repo's description made that more explicit, it was unclear for me too
> 
> Why would you want to use this without a namespace?

because i have already a pinecone database without namespaces and i want to use it .

**Comment by MoshiMaster** [comment]
do I actually need to change anything beside the .env? Was a bit confused with the pinecone.ts part
