### ISSUE TITLE
How to use HNSWLib to create and consume a vector store?

### ISSUE THREAD

**Issue by kevlozano** [mayooear/gpt4-pdf-chatbot-langchain#81]
Hey hi!

First of all thank you for all the work here. I really appreciate it.

I've been trying to create a script similar to `ingest-data` but using HNSWLib. So far no luck, I've followed langchain's example from the docs as well as the examples from HNSWLib-node docs but no luck yet. I keep getting `failed to ingest`. As I look into the error it seems I'm not splitting the pdf correctly.

Any guidance here would be appreciated.

**Comment by mayooear** [comment]
I think you may need to download VS Code to use `HNSWLib-node`. Try and test it on a standalone repo using LangChain.
