### ISSUE TITLE
When running “npm run ingest”, there is a “network error”, how to solve

### ISSUE THREAD

**Issue by kingsun1980** [mayooear/gpt4-pdf-chatbot-langchain#82]
The problem I'm having now is: whenever the program runs to creating vector store... After a minute or so, there will be a network error, indicating extraction failure! The screenshot is as follows I use gpt-3 in the configuration file, the pinecone and openai configurations are also configured, indexname is also the same as the one set in pinecone, Dimensions is set to 1536, and the index is in the ready state in the console. openai api parameters are also configured. In order to prevent the limitations of gpt-4, in the configuration also changed to gpt3 (in accordance with the format of the tips to change), now it is not clear what the problem is, gpt desktop version can be accessed normally at any time, pdf document I specifically selected a only 20 pages of English material, from the console logs, the content can be resolved, but it is stuck in the extraction here, please help to see, thank you!
![Uploading image.png…]()

**Comment by 15392778677** [comment]
> 
I add " pinecone.projectName = "xxxxx";but it also print errornetwork
