### ISSUE TITLE
where should I config for proxy?

### ISSUE THREAD

**Issue by dadaoerv** [mayooear/gpt4-pdf-chatbot-langchain#83]
export HTTP_PROXY=http://yourproxyhostname:yourproxyport

which config file should I put for proxy for openai.

thanks

**Comment by 15392778677** [comment]
hello，I also want to know

**Comment by LvisWang** [comment]
> export HTTP_PROXY=http://yourproxyhostname:yourproxyport
> 
> which config file should I put for proxy for openai.
> 
> thanks

did you figure it out ser?

**Comment by yinshipeng** [comment]
I tried it. It didn't work
