### ISSUE TITLE
How would I ingest text files instead of PDF files?

### ISSUE THREAD

**Issue by mrmachine** [mayooear/gpt4-pdf-chatbot-langchain#84]
I have text files generated by Whisper API that I would like to ingest, instead of PDFs. I did also try saving a Google Doc in PDF format but the PDF loader does not seem to load the text correctly.

PDF:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/51939/228809846-9a2512c2-df85-4919-8e71-eb68d96aee2e.png">

Context included in ChatGPT prompt:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/51939/228809996-b13ea3b2-3881-4a01-bffc-0ed9ffa77927.png">

**Comment by bschleter** [comment]
I still have some problems with vectors and things on Pinecone end, but I was at least able to ingest doing this and adding a .txt textloader path: 
`const filePath = 'docs';

export const run = async () => {
  try {
    const directoryloader = new DirectoryLoader(filePath, {
      '.pdf': (path) => new CustomPDFLoader(path),
      '.txt': (path) => new TextLoader(path),
    });
    
    const rawDocs = await directoryloader.load();

    console.log(rawDocs);
`

can't guarantee it'll work but it got me farther.

**Comment by tuantranf** [comment]
@dreamcreated I tried my side to ingest txt file using `TextLoader` of langchain/document_loaders
```
import { DirectoryLoader, TextLoader } from 'langchain/document_loaders';

const directoryLoader = new DirectoryLoader(filePath, {
      '.txt': (path) => new TextLoader(path),
    });

// const loader = new PDFLoader(filePath);
    const rawDocs = await directoryLoader.load();

    /* Split text into chunks */
    const textSplitter = new RecursiveCharacterTextSplitter({
      chunkSize: 1000,
      chunkOverlap: 200,
    });

    const docs = await textSplitter.splitDocuments(rawDocs);
    // console.log('split docs', docs);

```

**Comment by bschleter** [comment]
@dreamcreated i added .txt files of my own into the data folder. I tried it not using the predefined path with the default pdf, but the data folder as the path. In there I placed all my text files. So the text loader I added if I wasn't clear as I don't speak too good.
