### ISSUE TITLE
 “npm run ingest”, “network error”,  clashx，解决方案：clashx-pro

### ISSUE THREAD

**Issue by saodiawei** [mayooear/gpt4-pdf-chatbot-langchain#85]
如果是 mac 电脑遇到这个问题，可以安装 clashx-pro 解决，开启增强模式与全局代理后可以解决，分享给受折磨的朋友
---
If you encounter this problem on a Mac computer, you can install ClashX-Pro to solve it. After enabling the enhanced mode and global proxy, the problem can be solved. Share it with friends who are suffering from the same issue.

download：https://itlanyan.com/download.php?filename=/v2/macos/ClashX-Pro-v1.72.0.4.dmg

**Comment by kingsun1980** [comment]
Just what I need! I'll try it！！

**Comment by kingsun1980** [comment]
操作系统是windows

**Comment by kingsun1980** [comment]
我试一下

**Comment by linwentao-hexin** [comment]
> 我试一下

你尝试成功了吗，我开了全局代理，也设置了 HTTP_PROXY 也是不行诶

**Comment by yudidina** [comment]
> 



> > 我试一下
> 
> 你尝试成功了吗，我开了全局代理，也设置了 HTTP_PROXY 也是不行诶

我也是，开全局加设置proxy都不行，报错network error，好几天了都是这样

**Comment by 15392778677** [comment]
我也是

**Comment by 15392778677** [comment]
> 我试一下
成功了么，这个到底要怎么解决呀

**Comment by bobojiayou** [comment]
太感谢了，卡了几天了~~

**Comment by yudidina** [comment]
请问有人在windows上解决了这个问题吗

**Comment by kingsun1980** [comment]
我是在windows上使用了clash，打开TUN-model，走虚拟网卡，不要走http代理，因为在使用git命令的时候，使用cmd命令行默认从网卡走，不会从http代理走，所以会抛net error

**Comment by kingsun1980** [comment]
目前，配置好了tun，开了全局模式，但是仍然抛net error

**Comment by yudidina** [comment]
> 目前，配置好了tun，开了全局模式，但是仍然抛net error

你好，请问你解决了问题吗

**Comment by tiwentichat** [comment]
> 抱歉，windows 还没尝试过~我是关键词全局代理找到的解决方案，你也可以试试

兄弟救命，我mac,下载了clash开增强，vray全局，还是不行，failed to ingest，clashxpro需要什么单独设置吗？还是直接点增强就不用管了啊？
全局模式、美国节点

**Comment by ciiwhjp65** [comment]
我看到 windows 这么设置有可以的 
![image](https://user-images.githubusercontent.com/118330907/229774166-227ba7ff-5b5b-4541-990d-b69ce95ac79c.png)

**Comment by dongqf123** [comment]
有大哥们在windows配置成功的吗。。求怎么配置的
