### ISSUE TITLE
Auth / 401 error on ingestion

### ISSUE THREAD

**Issue by ComicDansMS** [mayooear/gpt4-pdf-chatbot-langchain#9]
I have updated the pinecone and OpenAI API keys in the env file, and my pinecone index matches the pinecone index name in pinecone.ts.

It seems that it's all fine on Pinecone's end. My pinecone API key seems to be fine as I can run `curl -i https://controller.us-central1-gcp.pinecone.io/actions/whoami -H 'API_KEY' ` without receiving an error. The initialisation of Pinecone in pinecone-client.ts seems to be fine with no errors.

I'm thinking it's a problem when dealing with the OpenAI API. My OpenAI API key has access to GPT-4 and works fine in another chatbot I created, so I know that's ok.

What seems weird (to my limited knowledge of the embeddings API) is that when I log the embeddings instance, the apiKey value is not my API key. It seems to look like an OpenAI API key but it is not mine. The key also doesn't exist anywhere in the codebase. This may be normal but it seems weird as this is also the place that it's throwing an error.

Here is the output when I log embeddings:
```
EMBEDDINGS:  OpenAIEmbeddings {
  modelName: 'text-embedding-ada-002',
  batchSize: 512,
  maxRetries: 6,
  stripNewLines: true,
  apiKey: 'sk-9Ng******j3Wun',
  client: undefined
}
```

I have tried creating a new openai key but still results in the same error.
It might be a problem on OpenAI's end. This seems a little similar to the problem here - https://community.openai.com/t/api-key-trouble/20017/10

**Comment by mayooear** [comment]
Thanks for this. Strange case here. Have you tested some of the solutions on that thread?

**Comment by ComicDansMS** [comment]
I've tried it out on my machine at work and it works fine!

That thread mentions clearing browser cache but obviously this step isn't browser based. This is what made me try it on my work machine. I'll try restarting my machine at home tonight as I only do it once every so often. For the most part this is fine though!

**Comment by ComicDansMS** [comment]
Restarting my machine didn't fix this.
I have cleared the cache in node.
I have re-installed node.
I deleted and re-cloned this repo (trying anything here).

Still errors out with the same OpenAI auth error while using the different API key that doesn't belong to me.

So strange.

**Comment by mayooear** [comment]
When you try the API key in isolation does it work? It doesn't seem like it's an issue with this repo.

**Comment by ComicDansMS** [comment]
Yeah that's what I've come to realise when it worked on my work machine. This repo is fine.
The API key works fine in other places. It also works ok in this repo from my work machine.

It's something specific to my computer at home. Feel free to close this issue. It's a me problem :) Just so weird though.

**Comment by janzheng** [comment]
Same thing is happening to me. If you just print the env variable, you'll see that _something seems to be replacing the env variable_. If I switch out all `process.env.OPENAI_API_KEY` to use `process.env.OPENAI_API_KEY2` then there's no problem.

I've never worked with Next before, but I'm betting on that some "magic" is happening in the background, which is supposed to help, but actually is just secretly replacing the keys with fake keys.

**Comment by mayooear** [comment]
> Same thing is happening to me. If you just print the env variable, you'll see that _something seems to be replacing the env variable_. If I switch out all `process.env.OPENAI_API_KEY` to use `process.env.OPENAI_API_KEY2` then there's no problem.
> 
> I've never worked with Next before, but I'm betting on that some "magic" is happening in the background, which is supposed to help, but actually is just secretly replacing the keys with fake keys.

@ComicDansMS can you confirm that this solution works?

**Comment by ComicDansMS** [comment]
That solution of renaming it didn't work (the embeddings instance still used the random key). But I did then try simply logging `process.env.OPENAI_API_KEY` and it was returning the other key. 

After I span up a fresh next-js project, threw in a .env file and logged it out in an endpoint, I still got the same random key. So that proved that it was my machine.

Then I remembered that I had used the terminal to try out the gpt api a long time ago and I stored the key in the machines environment variables. I checked them using `env` in the terminal and the same key is showing under `OPENAI_API_KEY`. So that explains what's going on and that it's nothing to do with this repo. I guess the langchain package could be better and take a defined environment variable, rather than having a set key that it relies on.

The only issue I'm having (my issue, not this repo) is that the `unset` command isn't removing it. It appears to remove it when I view the variables using `env` immediately after. But if I reload the terminal, it's back there again. That's something for me to figure out.

Although what I can't work out is why @janzheng got it working when he renamed his variable? I can't see anywhere in the langchain docs anything about using a different variable name.

So yeah, got to the bottom of it. It's not this repo.

**Comment by janzheng** [comment]
> That solution of renaming it didn't work (the embeddings instance still used the random key). But I did then try simply logging `process.env.OPENAI_API_KEY` and it was returning the other key.
> 
> After I span up a fresh next-js project, threw in a .env file and logged it out in an endpoint, I still got the same random key. So that proved that it was my machine.
> 
> Then I remembered that I had used the terminal to try out the gpt api a long time ago and I stored the key my .zshrc file. So I removed it, I had to also remove it from the mac's environment variables using `unset` as it ended up there too, and then had to restart the machine as it seemed to be stuck somehow (console logs were still returning it). So that explains what's going on and that it's nothing to do with this repo. It's just clashing with the same variable on my machine. I guess the langchain package could be better and take a defined environment variable, rather than having a set key that it relies on.
> 
> Although what I can't work out is why @janzheng got it working when he renamed his variable? I can't see anywhere in the langchain docs anything about using a different variable name.
> 
> So yeah. It was my machine. It's not this repo.

I had to manually set `process.env.OPENAI_API_KEY` everywhere OpenAI is called in the code. I actually had no idea it just looked for that env variable; I was confused as to why the API key wasn't explicitly passed in anywhere. 

I just did the same as you — and lo and behold my random key is also being stored the same way as you. Unlike you, I can't find where it's stored so I can't get rid of it... but for some reason this is ONLY happening on this project. Not the other projects, which all use the same env variable. Those are Sveltekit projects so... I don't know. Maybe it's something Next specific?

Anyway, I'd actually go the length to say this is all really odd, but probably not an error related to the project itself.

**Comment by mayooear** [comment]
@janzheng this is a very strange and difficult openai bug. What category of errors does this fall into for the sake of future users?

**Comment by ComicDansMS** [comment]
> I just did the same as you — and lo and behold my random key is also being stored the same way as you. Unlike you, I can't find where it's stored so I can't get rid of it... but for some reason this is ONLY happening on this project. Not the other projects, which all use the same env variable. Those are Sveltekit projects so... I don't know. Maybe it's something Next specific?

For me, it was stored in my `.zhsrc` file. It was still persistent but got rid of it with a restart of my machine.

- Removed variable from `.zhsrc`
- Ran `unset OPENAI_API_KEY` in terminal to remove the value from the shell's environment
- Checked to see if it's removed with the `env` command - Removal was successful
- Restarted terminal and ran `env` and found the variable was back again
- Opened my default user directory where `.zhsrc` lives in VS Code and did a global search of the key (nothing returned)
- Ran `unset OPENAI_API_KEY` and restarted the machine
- Checked for the variable using `env` - It hadn't returned
- Tried accessing `process.env.OPENAI_API_KEY` from a node app with a `.env` set - It returned the proper `.env` variable this time.

So yeah. I only know enough about the shell to get by, so maybe I missed something obvious, but that's how I ended up removing it.

I was also really confused as to why the API key wasn't passed in anywhere. I started going through the code of the langchain package and trying to trace everything out. Ended up reading the docs which seemed like an obvious first step. But here we are :)

**Comment by ComicDansMS** [comment]
> @janzheng this is a very strange and difficult openai bug. What category of errors does this fall into for the sake of future users?

I think it's just a users machine problem. What ever fancy name is given to that. 

I'm tossing up between thinking it's silly for a package to assume an environment variable name, but also thinking that it's a fine way to do it because who would store this sort of environment variable on their machine? It is the same name that OpenAI give it in their docs, afterall.

**Comment by mayooear** [comment]
> > @janzheng this is a very strange and difficult openai bug. What category of errors does this fall into for the sake of future users?
> 
> I think it's just a users machine problem. What ever fancy name is given to that.
> 
> I'm tossing up between thinking it's silly for a package to assume an environment variable name, but also thinking that it's a fine way to do it because who would store this sort of environment variable on their machine? It is the same name that OpenAI give it in their docs, afterall. It goes to show never assume anything I guess.

Is the repo code working now?

**Comment by ComicDansMS** [comment]
Yes it is
