### ISSUE TITLE
How to upload different PDFs

### ISSUE THREAD

**Issue by GMAN6875** [mayooear/gpt4-pdf-chatbot-langchain#90]
I am relatively new to all of this, I was able to ingest and run the program successfully and test the chatbot with the law pdf. I am trying to test with other PDF documents, I just pulled a science pdf (22 pages) and created a subfolder within docs called science and put it in. I then ingested it, but it seems to only ingest the law pdf from the repo. I deleted all other pdfs within the 'doc' folder and it seemed to ingest only the science doc but when I go to test on the UI it still acts as if it is the law doc. Am I missing something? Do I need to change the NAME SPACE for each pdf? What files and things should I be looking at for ingesting and interacting with new PDFs and how can I differentiate between folders? I noticed that both a 'law' and 'finance' folder are in the repo so I am assuming this isn't too complicated.

**Comment by user00001889** [comment]
I have the same issue/question as well

**Comment by smtdev** [comment]
The latest commit reads all the pdf files inside the `docs` directory, but not the subfolders inside it. You can find the code in [ingest-data.ts](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/blob/main/scripts/ingest-data.ts) file.

  ```
/* Name of directory to retrieve your files from */
  const filePath = 'docs';
  
  export const run = async () => {
    try {
      /*load raw docs from the all files in the directory */
      const directoryLoader = new DirectoryLoader(filePath, {
        '.pdf': (path) => new CustomPDFLoader(path),
      });
  
      // const loader = new PDFLoader(filePath);
      const rawDocs = await directoryLoader.load();
```

**Comment by user00001889** [comment]
But how to switch between the documents?

**Comment by mayooear** [comment]
> The latest commit reads all the pdf files inside the `docs` directory, but not the subfolders inside it. You can find the code in [ingest-data.ts](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/blob/main/scripts/ingest-data.ts) file.
> 
> ```
> /* Name of directory to retrieve your files from */
> const filePath = 'docs';
> 
> export const run = async () => {
>   try {
>     /*load raw docs from the all files in the directory */
>     const directoryLoader = new DirectoryLoader(filePath, {
>       '.pdf': (path) => new CustomPDFLoader(path),
>     });
> 
>     // const loader = new PDFLoader(filePath);
>     const rawDocs = await directoryLoader.load();
> ```
> 
> There is a [PR](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/pull/50) to improve the code.

The code reads the subdirectories recursively.

**Comment by DXXS** [comment]
I found that deleting the extant pinecone vectors before re-ingesting solved most issues where it seemed to think that the original docs were still available.

   However, it seems to be having issues chatting about my new documents; apparently it is reading each PDF page as a separate document and not remembering the page numbers, and then seems to get lost beyond about page 25 in an 80 page PDF, wherein it doesn't seem to be able to find results thereafter, claiming the information is ~'not in context'!?

**Comment by DXXS** [comment]
Then too, I had originally hoped I could just use symbolic links, but apparently it somehow doesn't recognize those as valid, nor OSX alias's either!?

**Comment by DXXS** [comment]
Bot should probably consult developers to verify if 'still relevant', as I haven't seen mention of associated fixes yet.
