### ISSUE TITLE
Issues ingesting pdf

### ISSUE THREAD

**Issue by snkrpapi212** [mayooear/gpt4-pdf-chatbot-langchain#93]
Hello I'm having issues ingesting pdfs. I tried with the two included files in the repo as well as other pdfs. Below is the error which complains about Project name not set.

```
creating vector store...
error [Error: PineconeClient: Project name not set. Call init() first.]
gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:44
    throw new Error('Failed to ingest your data');
          ^


[Error: Failed to ingest your data]

Node.js v19.7.0
```

I added a console log inside ingest-data.ts. Which shows my api key and environment, but projectName is undefined.

```
console.log(pinecone)

creating vector store...
PineconeClient {
  apiKey: 'xxxxxxxxx',
  projectName: undefined,
  environment: 'us-west4-gcp',
  configureIndexRaw: [Function (anonymous)],
  configureIndex: [Function (anonymous)],
  createCollectionRaw: [Function (anonymous)],
  createCollection: [Function (anonymous)],
  createIndexRaw: [Function (anonymous)],
  createIndex: [Function (anonymous)],
  deleteCollectionRaw: [Function (anonymous)],
  deleteCollection: [Function (anonymous)],
  deleteIndexRaw: [Function (anonymous)],
  deleteIndex: [Function (anonymous)],
  describeCollectionRaw: [Function (anonymous)],
  describeCollection: [Function (anonymous)],
  describeIndexRaw: [Function (anonymous)],
  describeIndex: [Function (anonymous)],
  listCollectionsRaw: [Function (anonymous)],
  listCollections: [Function (anonymous)],
  listIndexesRaw: [Function (anonymous)],
  listIndexes: [Function (anonymous)]
}
```

Thanks in advance.

**Comment by janek** [comment]
When I was debugging another issue and I entered an incorrect API key to see what happens, this is the error message that I was getting. So definitely double-check, and if that doesn't solve it, consider starting over like the readme suggests: 

> Pinecone errors
> 
> - Make sure your pinecone dashboard environment and index matches the one in the pinecone.ts and .env files.
> - Check that you've set the vector dimensions to 1536.
> - Make sure your pinecone namespace is in lowercase.
> - Pinecone indexes of users on the Starter(free) plan are deleted after 7 days of inactivity. To prevent this, send an API request to Pinecone to reset the counter.
> - Retry from scratch with a new Pinecone index and cloned rep

This worked for me when I was trying to solve the error message I was getting in #97

**Comment by snkrpapi212** [comment]
Thanks for pointing that out. It turns out it was using a apikey from my profile and not the one in the .env, issue is now resolved.
