### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by LvisWang** [mayooear/gpt4-pdf-chatbot-langchain#95]
![image](https://user-images.githubusercontent.com/85268534/229066065-dcf5c50f-488e-41aa-9bf8-4f49babee94f.png)
I successfully ingested my data and run the localhost.  When I tried to ask some qustions I get this network error

**Comment by anitman** [comment]
Make sure you are eligible to access gpt-4, otherwise you'll need to change the modelName in makechain.ts to gpt-3.5-turbo.

**Comment by prophesy604** [comment]
I'm trying to get this to run locally .. but for some odd reason it keeps ignoring my .env file.. thoughts?

**Comment by prophesy604** [comment]
I'm trying to get this to run locally .. but for some odd reason it keeps ignoring my .env file.. thoughts? any help would be appreciated

**Comment by LvisWang** [comment]
> 

Did you try 'export' ser?

**Comment by LvisWang** [comment]
> Make sure you are eligible to access gpt-4, otherwise you'll need to change the modelName in makechain.ts to gpt-3.5-turbo.

I guess yes, already upgrated my plan to gptPLUS

**Comment by prophesy604** [comment]
> > 
> 
> Did you try 'export' ser?

sorry, what do you mean?

**Comment by LvisWang** [comment]
> > > 
> > 
> > 
> > Did you try 'export' ser?
> 
> sorry, what do you mean?

try 'export OPENAI_API_KEY=' , this CL puts variable in you environment 

https://github.com/mayooear/gpt4-pdf-chatbot-langchain#:~:text=Try%20to%20hard%20code%20your%20API%20keys%20into%20the%20process.env%20variables.

**Comment by prophesy604** [comment]
> > > > 
> > > 
> > > 
> > > Did you try 'export' ser?
> > 
> > 
> > sorry, what do you mean?
> 
> try 'export OPENAI_API_KEY=' , this CL puts variable in you environment
> 
> https://github.com/mayooear/gpt4-pdf-chatbot-langchain#:~:text=Try%20to%20hard%20code%20your%20API%20keys%20into%20the%20process.env%20variables.

oh that worked! thanks. 

so i ran the ingest command it was working but after awhile it  gave failed to ingest your data

and this is the turingfinance.pdf

![image](https://user-images.githubusercontent.com/2389662/229398493-d7432958-c56a-4299-92b1-e57b591c055b.png)

any thought on this?

**Comment by prophesy604** [comment]
> > > > 
> > > 
> > > 
> > > Did you try 'export' ser?
> > 
> > 
> > sorry, what do you mean?
> 
> try 'export OPENAI_API_KEY=' , this CL puts variable in you environment
> 
> https://github.com/mayooear/gpt4-pdf-chatbot-langchain#:~:text=Try%20to%20hard%20code%20your%20API%20keys%20into%20the%20process.env%20variables.

ahh thanks! that worked!

**Comment by anitman** [comment]
> > Make sure you are eligible to access gpt-4, otherwise you'll need to change the modelName in makechain.ts to gpt-3.5-turbo.
> 
> I guess yes, already upgrated my plan to gptPLUS

Gptplus account will not let you access gpt-4 api, you have to add yourself to the waiting list and wait to get exclusive gpt-4 api via email. Gpt4 api key is not the same as gpt3.5's.

**Comment by billyjingxuan** [comment]
Did you solve the problem? I'm facing the same issue.
