### ISSUE TITLE
Deleting Vectors from Pinecone Index

### ISSUE THREAD

**Issue by R3TAL5** [mayooear/gpt4-pdf-chatbot-langchain#96]
Maybe I just missed something, but how do I delete data that has been ingested by Pinecone? Deleting PDFs from the docs section doesn't seem to stop the program from using the deleted documents and citing them as in your docs folder. I couldn't figure out how to delete the vectors in the index because I couldn't find the Vector IDs. I'm fairly new to this, so please explain it to me like I'm an idiot.

**Comment by mayooear** [comment]
As per [pinecone docs](https://docs.pinecone.io/docs/node-client), if you want to delete a PDF you'd delete the namespace the PDF is contained within and re-ingest as @darkomking noted. If you want to delete specific chunks within the PDF you'd need to know the ID of the vector, which you can get by first running a query.

**Comment by groovybits** [comment]
I deleted a specific document this way, by referencing the source filename, which avoided deleting the whole namespace.

```
curl -i -X POST 'https://INDEX-IDSTRING.svc.REGION.pinecone.io/vectors/delete?namespace=NAMESPACE' \
  -H 'Api-Key: API_KEY_HERE' \
  -H 'Content-Type: application/json' \
  -d '{
    "filter": {"source": {"$in": ["/Users/username/src/gpt4-pdf-chatbot-langchain/docs/ALL.pdf"]}}
  }'
```
